from fpdf import FPDF
from datetime import datetime

class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 20)
        self.set_text_color(44, 62, 80)
        self.cell(0, 10, 'Daily Brief', 0, 1, 'L')
        self.set_font('Arial', '', 11)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, 'Saturday, May 9, 2026 | 8:09 AM CDT', 0, 1, 'L')
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, f'Generated by Daily Brief Agent | Data as of May 8, 2026 market close', 0, 0, 'C')

pdf = PDF()
pdf.add_page()
pdf.set_auto_page_break(auto=True, margin=15)

# Executive Summary
pdf.set_fill_color(248, 249, 250)
pdf.set_draw_color(44, 62, 80)
pdf.set_font('Arial', 'B', 11)
pdf.set_text_color(44, 62, 80)
pdf.cell(0, 8, 'Executive Summary:', 0, 1, 'L')
pdf.set_font('Arial', '', 10)
pdf.set_text_color(30, 30, 30)
pdf.multi_cell(0, 5, 'Markets closed the week on a high note with the S&P 500 and Nasdaq hitting fresh record highs. Strong April jobs data (+115K vs forecast) and continued AI optimism fueled gains. Semiconductor stocks led the charge with Nvidia up 2.3% and Apple gaining 1.8%. Markets posted their 6th consecutive week of gains.', 0, 'L', True)
pdf.ln(5)

# Market Performance
pdf.set_font('Arial', 'B', 14)
pdf.set_text_color(44, 62, 80)
pdf.cell(0, 10, 'Market Performance', 0, 1, 'L')
pdf.ln(2)

# Table header
pdf.set_fill_color(44, 62, 80)
pdf.set_text_color(255, 255, 255)
pdf.set_font('Arial', 'B', 10)
pdf.cell(95, 8, 'Index', 1, 0, 'L', True)
pdf.cell(95, 8, 'Performance', 1, 1, 'R', True)

# Data rows
data = [
    ('S&P 500 (^GSPC)', '+0.8% - 7,399 (Record High)'),
    ('Nasdaq Composite (^IXIC)', '+1.7% - 26,247 (Record High)'),
    ('Dow Jones (^DJI)', '+0.05% - 49,609'),
    ('Philadelphia Semiconductor (^SOX)', 'New Record High'),
]

pdf.set_font('Arial', '', 10)
for i, (index, perf) in enumerate(data):
    if i % 2 == 0:
        pdf.set_fill_color(241, 241, 241)
    else:
        pdf.set_fill_color(255, 255, 255)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(95, 7, index, 1, 0, 'L', True)
    pdf.set_text_color(39, 174, 96)
    pdf.cell(95, 7, perf, 1, 1, 'R', True)

pdf.ln(5)

# Key Developments
pdf.set_font('Arial', 'B', 14)
pdf.set_text_color(44, 62, 80)
pdf.cell(0, 10, 'Key Developments', 0, 1, 'L')
pdf.ln(2)

developments = [
    ('Labor Market Shows Resilience', 
     'April nonfarm payrolls increased by 115,000, beating forecasts. Unemployment rate held steady at 4.3%. Hiring broadened across sectors, signaling improving labor market breadth. This "Goldilocks" report suggests the Fed will likely hold rates steady in the 3.50%-3.75% range through year-end.'),
    
    ('Apple-Intel Chip Deal Reported', 
     'Apple and Intel have reportedly reached a preliminary agreement for Intel to manufacture chips for Apple devices. This would be the first time Apple diversifies beyond TSMC for advanced chips. Intel shares surged nearly 14% on the news. The deal signals a major vote of confidence in Intel\'s foundry business (up 200%+ YTD).'),
    
    ('AI Demand Drives Chip Rally', 
     'Micron Technology and SanDisk surged sharply alongside Nvidia and Apple as optimism around AI infrastructure spending continues. 83% of S&P 500 companies that have reported Q1 results have beaten estimates, well above the 67% long-term average.'),
    
    ('Geopolitical Tensions Persist', 
     'US-Iran tensions remain elevated with continued clashes in the Strait of Hormuz. Brent crude rose above $100/barrel. President Trump stated the ceasefire remains intact, and markets await Tehran\'s response to the latest US proposal.'),
]

for title, content in developments:
    pdf.set_font('Arial', 'B', 11)
    pdf.set_text_color(52, 73, 94)
    pdf.cell(0, 6, title, 0, 1, 'L')
    pdf.set_font('Arial', '', 10)
    pdf.set_text_color(30, 30, 30)
    pdf.multi_cell(0, 5, content, 0, 'L')
    pdf.ln(3)

# Notable Movers
pdf.set_font('Arial', 'B', 14)
pdf.set_text_color(44, 62, 80)
pdf.cell(0, 10, 'Notable Movers', 0, 1, 'L')
pdf.ln(2)

movers = [
    'Nvidia (NVDA): +2.3% — Hit new 52-week high',
    'Apple (AAPL): +1.8% — Record high close',
    'Intel (INTC): +14% — Apple chip deal news',
    'Micron Technology: Sharp gains on AI demand',
    'SanDisk: Strong rally with semiconductor sector',
    'Cloudflare (NET): -24.4% — 20% workforce cut announced',
    'Trade Desk (TTD): -6.2% — Q2 revenue forecast below estimates',
    'CoreWeave (CRWV): -13% — Raised guidance concerns',
]

pdf.set_font('Arial', '', 10)
pdf.set_text_color(30, 30, 30)
for mover in movers:
    if ' -' in mover or '(' in mover and ')' in mover and 'NET' in mover or 'TTD' in mover or 'CRWV' in mover:
        pdf.set_text_color(231, 76, 60)  # Red for negative
    else:
        pdf.set_text_color(39, 174, 96)  # Green for positive
    pdf.cell(5, 5, '•', 0, 0, 'L')
    pdf.set_text_color(30, 30, 30)
    pdf.multi_cell(0, 5, mover, 0, 'L')

pdf.ln(5)

# Week Ahead
pdf.set_font('Arial', 'B', 14)
pdf.set_text_color(44, 62, 80)
pdf.cell(0, 10, 'Week Ahead Preview', 0, 1, 'L')
pdf.ln(2)

ahead_items = [
    'Markets will monitor ongoing Middle East developments',
    'Energy prices remain elevated; watch for inflation impacts',
    'Fed speakers may provide additional rate guidance',
    'Earnings season winding down with ~440 of 500 S&P companies reported',
]

pdf.set_font('Arial', '', 10)
pdf.set_text_color(30, 30, 30)
for item in ahead_items:
    pdf.cell(5, 5, '•', 0, 0, 'L')
    pdf.multi_cell(0, 5, item, 0, 'L')

# Save
output_path = r'C:\Users\thadd\OneDrive\Desktop\Spocks Reports\Daily_Brief_2026-05-09.pdf'
pdf.output(output_path)
print(f'PDF generated: {output_path}')