from fpdf import FPDF
import os

class PDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(26, 54, 93)
        self.cell(0, 10, 'History Rhymes - Market Pattern Analysis', new_x='LMARGIN', new_y='NEXT', align='L')
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, 'Historical Parallels to Current Market Conditions', new_x='LMARGIN', new_y='NEXT', align='L')
        self.cell(0, 6, 'May 17, 2026', new_x='LMARGIN', new_y='NEXT', align='L')
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def chapter_title(self, title):
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(44, 82, 130)
        self.cell(0, 10, title, new_x='LMARGIN', new_y='NEXT', align='L')
        self.ln(2)

    def section_title(self, title):
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(74, 85, 104)
        self.cell(0, 8, title, new_x='LMARGIN', new_y='NEXT', align='L')
        self.ln(1)

    def body_text(self, text):
        self.set_font('Helvetica', '', 10)
        self.set_text_color(51, 51, 51)
        self.multi_cell(0, 6, text)
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by History Rhymes Agent | Not investment advice | Page {self.page_no()}', align='C')

# Create output directory
output_dir = r'C:\Users\thadd\OneDrive\Desktop\Spocks Reports\history_rhymes'
os.makedirs(output_dir, exist_ok=True)

pdf = PDF()
pdf.add_page()

# Executive Summary
pdf.set_fill_color(235, 248, 255)
pdf.set_font('Helvetica', '', 10)
pdf.set_text_color(51, 51, 51)
pdf.multi_cell(0, 6, 'Executive Summary: Current market conditions show striking parallels to multiple historical periods: the 2000 Dot-Com Bubble (valuation concentration), the 2007 Pre-Financial Crisis (macro setup), and the 1960s-70s (geopolitical influence). The Shiller CAPE ratio at ~40-42 is the second-highest in 155 years.', fill=True)
pdf.ln(5)

# Current Market Snapshot
pdf.chapter_title('Current Market Snapshot')

pdf.set_font('Helvetica', 'B', 9)
pdf.set_fill_color(44, 82, 130)
pdf.set_text_color(255, 255, 255)
pdf.cell(55, 7, 'Metric', align='L', fill=True)
pdf.cell(45, 7, 'Current (May 2026)', align='C', fill=True)
pdf.cell(0, 7, 'Historical Context', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_text_color(51, 51, 51)
pdf.set_fill_color(247, 250, 252)
pdf.set_font('Helvetica', '', 9)
pdf.cell(55, 6, 'Shiller CAPE Ratio', align='L', fill=True)
pdf.set_font('Helvetica', 'B', 9)
pdf.set_text_color(44, 82, 130)
pdf.cell(45, 6, '40-42', align='C', fill=True)
pdf.set_font('Helvetica', '', 9)
pdf.set_text_color(51, 51, 51)
pdf.cell(0, 6, '2nd highest in 155 years', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(255, 255, 255)
pdf.cell(55, 6, 'S&P 500 Forward P/E', align='L', fill=False)
pdf.set_font('Helvetica', 'B', 9)
pdf.cell(45, 6, '~22x', align='C', fill=False)
pdf.set_font('Helvetica', '', 9)
pdf.cell(0, 6, 'Lower than 2000 (27x)', align='L', fill=False, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(247, 250, 252)
pdf.cell(55, 6, 'Top-10 Concentration', align='L', fill=True)
pdf.set_font('Helvetica', 'B', 9)
pdf.set_text_color(229, 62, 62)
pdf.cell(45, 6, '36-40%', align='C', fill=True)
pdf.set_font('Helvetica', '', 9)
pdf.set_text_color(51, 51, 51)
pdf.cell(0, 6, '50% ABOVE dot-com peak (27%)', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(255, 255, 255)
pdf.cell(55, 6, '10-Year Treasury Yield', align='L', fill=False)
pdf.set_font('Helvetica', 'B', 9)
pdf.cell(45, 6, '4.47%', align='C', fill=False)
pdf.set_font('Helvetica', '', 9)
pdf.cell(0, 6, 'Pressuring growth valuations', align='L', fill=False, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(247, 250, 252)
pdf.cell(55, 6, 'Tech Sector % of S&P 500', align='L', fill=True)
pdf.set_font('Helvetica', 'B', 9)
pdf.cell(45, 6, '32%', align='C', fill=True)
pdf.set_font('Helvetica', '', 9)
pdf.cell(0, 6, 'Similar to dot-com peak (33%)', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(255, 255, 255)
pdf.cell(55, 6, 'CPI Inflation', align='L', fill=False)
pdf.set_font('Helvetica', 'B', 9)
pdf.cell(45, 6, '3.3%', align='C', fill=False)
pdf.set_font('Helvetica', '', 9)
pdf.cell(0, 6, 'Sticky - above Fed target', align='L', fill=False, new_x='LMARGIN', new_y='NEXT')
pdf.ln(5)

# Historical Parallels
pdf.chapter_title('Key Historical Parallels')

# Dot-Com Section
pdf.section_title('1. The 1999-2000 Dot-Com Bubble [HIGH SIMILARITY]')

pdf.set_font('Helvetica', 'B', 9)
pdf.set_fill_color(44, 82, 130)
pdf.set_text_color(255, 255, 255)
pdf.cell(50, 7, 'Metric', align='L', fill=True)
pdf.cell(35, 7, 'March 2000', align='C', fill=True)
pdf.cell(0, 7, 'March 2026', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_text_color(51, 51, 51)
pdf.set_fill_color(247, 250, 252)
pdf.set_font('Helvetica', '', 9)
pdf.cell(50, 6, 'S&P 500 Forward P/E', align='L', fill=True)
pdf.cell(35, 6, '27x', align='C', fill=True)
pdf.cell(0, 6, '22x', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(255, 255, 255)
pdf.cell(50, 6, 'Top-10 Concentration', align='L', fill=False)
pdf.cell(35, 6, '27%', align='C', fill=False)
pdf.set_text_color(229, 62, 62)
pdf.cell(0, 6, '36% (+50% vs 2000)', align='L', fill=False, new_x='LMARGIN', new_y='NEXT')
pdf.set_text_color(51, 51, 51)

pdf.set_fill_color(247, 250, 252)
pdf.cell(50, 6, 'CAPE Ratio', align='L', fill=True)
pdf.cell(35, 6, '44.19 (peak)', align='C', fill=True)
pdf.cell(0, 6, '38-42', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(255, 255, 255)
pdf.cell(50, 6, '10-Year Treasury', align='L', fill=False)
pdf.cell(35, 6, '6.0%', align='C', fill=False)
pdf.cell(0, 6, '4.3-4.5%', align='L', fill=False, new_x='LMARGIN', new_y='NEXT')

pdf.ln(3)
pdf.set_fill_color(235, 248, 255)
pdf.set_font('Helvetica', '', 10)
pdf.multi_cell(0, 6, 'Key Rhyme Pattern: Valuation extremes and concentration risk mirror the dot-com era, though today\'s companies are actually profitable. NVIDIA generates ~$60B in free cash flow vs Microsoft\'s $11B in 2000. The question: can $660-690B in annual hyperscaler capex generate sufficient returns?', fill=True)
pdf.ln(5)

# 2007 Section
pdf.add_page()
pdf.section_title('2. May 2007 Pre-Financial Crisis [HIGH SIMILARITY]')
pdf.body_text('According to Prospero.ai analysis, 2026 macro conditions show eerie similarities to May 2007:')

pdf.set_font('Helvetica', 'B', 9)
pdf.set_fill_color(44, 82, 130)
pdf.set_text_color(255, 255, 255)
pdf.cell(40, 7, 'Factor', align='L', fill=True)
pdf.cell(35, 7, 'May 2007', align='C', fill=True)
pdf.cell(0, 7, 'May 2026', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_text_color(51, 51, 51)
pdf.set_fill_color(247, 250, 252)
pdf.set_font('Helvetica', '', 9)
pdf.cell(40, 6, 'Inflation', align='L', fill=True)
pdf.cell(35, 6, 'Sticky', align='C', fill=True)
pdf.cell(0, 6, 'CPI 3.3% - sticky above target', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(255, 255, 255)
pdf.cell(40, 6, 'Oil Prices', align='L', fill=False)
pdf.cell(35, 6, 'Rising', align='C', fill=False)
pdf.cell(0, 6, '$100+ WTI (Iran conflict)', align='L', fill=False, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(247, 250, 252)
pdf.cell(40, 6, 'Unemployment', align='L', fill=True)
pdf.cell(35, 6, 'Low/stable', align='C', fill=True)
pdf.cell(0, 6, '4.3% - "low-hire, low-fire"', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(255, 255, 255)
pdf.cell(40, 6, 'Consumer Sentiment', align='L', fill=False)
pdf.cell(35, 6, 'Slipping', align='C', fill=False)
pdf.cell(0, 6, '49.8 - lowest in data series', align='L', fill=False, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(247, 250, 252)
pdf.cell(40, 6, 'Market Leadership', align='L', fill=True)
pdf.cell(35, 6, 'Tech strong', align='C', fill=True)
pdf.cell(0, 6, 'Apple, Google resilient', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.ln(3)
pdf.set_fill_color(255, 245, 245)
pdf.set_text_color(229, 62, 62)
pdf.set_font('Helvetica', '', 10)
pdf.multi_cell(0, 6, 'Cautionary Note: In May 2007, the S&P broke above its dot-com high of 1,527. Earnings were strong, volatility low, credit spreads tight. The bull narrative felt unstoppable. Yet subprime cracks were already showing. History may not repeat, but it rhymes.', fill=True)
pdf.set_text_color(51, 51, 51)
pdf.ln(5)

# 1960s-70s Section
pdf.section_title('3. The 1960s-70s: Geopolitics & Trade Wars [MEDIUM SIMILARITY]')
pdf.body_text("State Street's 'History Rhymes Again' analysis identifies a structural shift back toward a 1960s-70s era regime:")

pdf.body_text("- Geopolitics dominant: China's rise = Japan's rise in 1960s-70s (trade tensions)")
pdf.body_text("- Growing trade deficits: US struggling with manufacturing dependency")
pdf.body_text("- Reshoring movement: CHIPS Act (2022), Brexit (2016), anti-globalization backlash")
pdf.body_text("- Rising nationalism: Tariffs, 'America First' policies")
pdf.body_text("- Inflation dynamics: Questions about transitory vs structural")
pdf.ln(3)

# The Rhyme Patterns
pdf.chapter_title('The Rhyme Patterns')

pdf.section_title('Pattern 1: Valuation Extremes [CRITICAL]')
pdf.body_text('The Shiller CAPE at 40-42 has only been exceeded once (March 2000). 57% of institutional investors now identify an AI valuation crash as the single greatest market risk per Deutsche Bank survey. Jeremy Grantham (who called dot-com and housing bubbles) says there is "slim to none" chance the current AI rally does not end in a bust.')

pdf.section_title('Pattern 2: Concentration Risk [CRITICAL]')
pdf.body_text("The top 10 stocks now represent 36-40% of the S&P 500 - nearly 50% above dot-com levels. This means the market's fate rests on fewer companies than at any point since data began.")

pdf.section_title('Pattern 3: Capex Intensity [WATCH]')
pdf.body_text("Hyperscaler AI capex (~$320B annually from Big 4) is an order of magnitude larger than the dot-com telecom buildout (~$30B). The question isn't whether AI is real - it's whether the infrastructure spending will generate proportional returns.")

pdf.section_title('Pattern 4: Macro Fragility [WATCH]')
pdf.body_text('Sticky inflation, elevated oil, softening labor data, and record-low consumer sentiment despite market highs create a familiar pre-crisis macro setup reminiscent of 2007.')

# Historical Outcomes
pdf.add_page()
pdf.chapter_title('Historical Outcomes to Consider')

pdf.set_font('Helvetica', 'B', 9)
pdf.set_fill_color(44, 82, 130)
pdf.set_text_color(255, 255, 255)
pdf.cell(50, 7, 'Parallel', align='L', fill=True)
pdf.cell(55, 7, 'Historical Outcome', align='C', fill=True)
pdf.cell(0, 7, 'Timeline', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_text_color(51, 51, 51)
pdf.set_fill_color(247, 250, 252)
pdf.set_font('Helvetica', '', 9)
pdf.cell(50, 7, 'Dot-Com Peak (Mar 2000)', align='L', fill=True)
pdf.set_text_color(229, 62, 62)
pdf.cell(55, 7, 'Nasdaq -78%, S&P -49%', align='C', fill=True)
pdf.set_text_color(51, 51, 51)
pdf.cell(0, 7, '2.5 years to bottom', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(255, 255, 255)
pdf.cell(50, 7, 'May 2007 Peak', align='L', fill=False)
pdf.set_text_color(229, 62, 62)
pdf.cell(55, 7, 'S&P -57% during GFC', align='C', fill=False)
pdf.set_text_color(51, 51, 51)
pdf.cell(0, 7, '17 months to bottom', align='L', fill=False, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(247, 250, 252)
pdf.cell(50, 7, '1960s-70s Regime', align='L', fill=True)
pdf.cell(55, 7, 'Stagflation, lost decade', align='C', fill=True)
pdf.cell(0, 7, '10+ years sideways', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(255, 255, 255)
pdf.cell(50, 7, '1987 Black Monday', align='L', fill=False)
pdf.cell(55, 7, '-22% single day', align='C', fill=False)
pdf.cell(0, 7, 'Flash crash, quick recovery', align='L', fill=False, new_x='LMARGIN', new_y='NEXT')
pdf.ln(5)

# Key Differences
pdf.chapter_title('Key Differences from Past Cycles')
pdf.set_fill_color(235, 248, 255)
pdf.set_font('Helvetica', '', 10)
pdf.multi_cell(0, 6, 'Why This Time Might Be Different (Bull Case): AI companies are actually profitable - unlike dot-com era. NVIDIA ROE: ~85% vs Microsoft\'s ~25% in 2000. Lower forward P/E (22x vs 27x in 2000). Cooler IPO market (156 vs 477 in 1999). Lower 10-year yields (4.5% vs 6.0% in 2000). More disciplined hyperscaler balance sheets.', fill=True)
pdf.ln(5)

# Risk Summary
pdf.set_fill_color(255, 245, 245)
pdf.set_text_color(229, 62, 62)
pdf.set_font('Helvetica', 'B', 10)
pdf.cell(0, 6, 'Primary Risks:', new_x='LMARGIN', new_y='NEXT', align='L')
pdf.set_font('Helvetica', '', 10)
pdf.multi_cell(0, 6, '1. Valuation Crash: CAPE at historic extremes suggests limited upside, significant downside. 2. Concentration Cascade: If MAG7/AI leaders falter, broad market follows. 3. Capex Cliff: $660-690B annual spend must generate returns. 4. Macro Unwind: 2007-style fragility with sticky inflation. 5. Geopolitical Shock: 1960s-style trade wars.', fill=True)
pdf.set_text_color(51, 51, 51)
pdf.ln(5)

# Conclusion
pdf.add_page()
pdf.chapter_title('Conclusion')
pdf.body_text('Mark Twain\'s quote rings true: "History doesn\'t repeat itself, but it often rhymes." Current conditions show compelling parallels to three distinct historical periods:')

pdf.set_font('Helvetica', 'B', 10)
pdf.cell(0, 6, '1. Dot-Com Bubble (1999-2000):', new_x='LMARGIN', new_y='NEXT', align='L')
pdf.set_font('Helvetica', '', 10)
pdf.cell(0, 6, '   Extreme valuations, high concentration, tech dominance', new_x='LMARGIN', new_y='NEXT', align='L')
pdf.ln(2)

pdf.set_font('Helvetica', 'B', 10)
pdf.cell(0, 6, '2. Pre-GFC (2007):', new_x='LMARGIN', new_y='NEXT', align='L')
pdf.set_font('Helvetica', '', 10)
pdf.cell(0, 6, '   Complacent macro, soft data beneath market highs, cracks forming', new_x='LMARGIN', new_y='NEXT', align='L')
pdf.ln(2)

pdf.set_font('Helvetica', 'B', 10)
pdf.cell(0, 6, '3. 1960s-70s:', new_x='LMARGIN', new_y='NEXT', align='L')
pdf.set_font('Helvetica', '', 10)
pdf.cell(0, 6, '   Geopolitical trade wars, inflation questions, regime shift', new_x='LMARGIN', new_y='NEXT', align='L')
pdf.ln(5)

pdf.body_text('The unique element is that all three patterns are simultaneously present. History suggests caution is warranted. The resolution depends on whether AI can deliver returns commensurate with the investment - a question that cannot be answered until the infrastructure cycle produces measurable results.')

# Save PDF
output_path = os.path.join(output_dir, '2026-05-17_history_rhymes.pdf')
pdf.output(output_path)
print(f'PDF generated: {output_path}')
