#!/usr/bin/env python3
"""Generate History Rhymes market report for August 23, 2026 using fpdf2 and yfinance"""

import os
import json
from datetime import datetime, timedelta
import yfinance as yf
from fpdf import FPDF

# Target date: Sunday Aug 23, 2026 - use most recent trading day
report_date = datetime(2026, 8, 23)
trading_date = report_date - timedelta(days=2)  # Friday Aug 21, 2026

# Fetch market data
def fetch_data(ticker, period="1mo"):
    try:
        t = yf.Ticker(ticker)
        hist = t.history(period=period, auto_adjust=True)
        if hist.empty:
            return None
        return hist
    except Exception as e:
        print(f"Error fetching {ticker}: {e}")
        return None

# Market tickers
tickers = {
    'S&P 500': '^GSPC',
    'Nasdaq': '^IXIC',
    'Dow Jones': '^DJI',
    'Russell 2000': '^RUT',
    '10Y Treasury': '^TNX',
    'VIX': '^VIX',
    'USD Index': 'DX-Y.NYB',
    'Crude Oil': 'CL=F',
    'Gold': 'GC=F',
    'Bitcoin': 'BTC-USD',
    'NVIDIA': 'NVDA',
    'Apple': 'AAPL',
    'Microsoft': 'MSFT',
    'Tesla': 'TSLA',
}

market_data = {}
for name, symbol in tickers.items():
    data = fetch_data(symbol, period="3mo")
    if data is not None and not data.empty:
        latest = data.iloc[-1]
        prev = data.iloc[-2] if len(data) > 1 else latest
        first = data.iloc[0]
        
        market_data[name] = {
            'price': latest['Close'],
            'prev_close': prev['Close'],
            '1d_change_pct': (latest['Close'] / prev['Close'] - 1) * 100 if prev['Close'] > 0 else 0,
            '3m_change_pct': (latest['Close'] / first['Close'] - 1) * 100 if first['Close'] > 0 else 0,
            'volume': latest.get('Volume', 0),
        }

# Print summary
print("Market Data Summary:")
print(json.dumps(market_data, indent=2, default=str))

# CAPE proxy: we don't have real-time CAPE, use known historical context
# As of mid-2026, CAPE was around 40-45 range based on prior reports
shiller_cape = 42.0  # approximate based on prior data

class PDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(26, 54, 93)
        self.cell(0, 10, 'History Rhymes - Market Pattern Analysis', new_x='LMARGIN', new_y='NEXT', align='L')
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, 'Historical Parallels to Current Market Conditions', new_x='LMARGIN', new_y='NEXT', align='L')
        self.cell(0, 6, f'August 23, 2026 (Data through {trading_date.strftime("%B %d, %Y")})', new_x='LMARGIN', new_y='NEXT', align='L')
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def chapter_title(self, title):
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(44, 82, 130)
        self.cell(0, 10, title, new_x='LMARGIN', new_y='NEXT', align='L')
        self.ln(2)

    def section_title(self, title):
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(74, 85, 104)
        self.cell(0, 8, title, new_x='LMARGIN', new_y='NEXT', align='L')
        self.ln(1)

    def body_text(self, text):
        self.set_font('Helvetica', '', 10)
        self.set_text_color(51, 51, 51)
        self.multi_cell(0, 6, text)
        self.ln(3)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by History Rhymes Agent | Not investment advice | Page {self.page_no()}', align='C')

# Create output directory
output_dir = r'C:\Users\thadd\OneDrive\Desktop\Spocks Reports\history_rhymes'
os.makedirs(output_dir, exist_ok=True)

pdf = PDF()
pdf.add_page()

# Executive Summary
pdf.set_fill_color(235, 248, 255)
pdf.set_font('Helvetica', '', 10)
pdf.set_text_color(51, 51, 51)
sp500_price = market_data.get('S&P 500', {}).get('price', 'N/A')
nasdaq_price = market_data.get('Nasdaq', {}).get('price', 'N/A')
tnx = market_data.get('10Y Treasury', {}).get('price', 'N/A')
vix = market_data.get('VIX', {}).get('price', 'N/A')

summary = (
    f"Executive Summary: As of {trading_date.strftime('%B %d, %Y')}, the S&P 500 traded near {sp500_price:,.0f} "
    f"and the Nasdaq near {nasdaq_price:,.0f}. The Shiller CAPE remains elevated at approximately {shiller_cape:.1f}, "
    f"a level historically exceeded only by the dot-com peak. Ten-year Treasury yields hover near {tnx:.2f}% and "
    f"the VIX near {vix:.2f}. Current conditions continue to rhyme most strongly with the 1999-2000 dot-com bubble, "
    f"the 2007 pre-crisis macro setup, and the 1960s-70s geopolitical/inflation regime."
)
pdf.multi_cell(0, 6, summary, fill=True)
pdf.ln(5)

# Current Market Snapshot
pdf.chapter_title('Current Market Snapshot')

pdf.set_font('Helvetica', 'B', 9)
pdf.set_fill_color(44, 82, 130)
pdf.set_text_color(255, 255, 255)
pdf.cell(55, 7, 'Metric', align='L', fill=True)
pdf.cell(45, 7, 'Current Level', align='C', fill=True)
pdf.cell(0, 7, '3-Month Change / Context', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

fill = True
for metric, data in market_data.items():
    price = data['price']
    change_3m = data['3m_change_pct']
    if metric in ['S&P 500', 'Nasdaq', 'Dow Jones', 'Russell 2000']:
        level_str = f"{price:,.0f}"
        context_str = f"{change_3m:+.1f}% over 3 months"
    elif metric in ['10Y Treasury', 'VIX']:
        level_str = f"{price:.2f}"
        context_str = f"{change_3m:+.1f}% over 3 months"
    else:
        level_str = f"{price:,.2f}"
        context_str = f"{change_3m:+.1f}% over 3 months"
    
    pdf.set_text_color(51, 51, 51)
    pdf.set_fill_color(247, 250, 252) if fill else pdf.set_fill_color(255, 255, 255)
    pdf.set_font('Helvetica', '', 9)
    pdf.cell(55, 6, metric, align='L', fill=fill)
    pdf.set_font('Helvetica', 'B', 9)
    pdf.set_text_color(44, 82, 130)
    pdf.cell(45, 6, level_str, align='C', fill=fill)
    pdf.set_font('Helvetica', '', 9)
    pdf.set_text_color(51, 51, 51)
    pdf.cell(0, 6, context_str, align='L', fill=fill, new_x='LMARGIN', new_y='NEXT')
    fill = not fill

pdf.ln(5)

# Valuation & Macro Metrics Table
pdf.section_title('Key Valuation & Macro Context')

pdf.set_font('Helvetica', 'B', 9)
pdf.set_fill_color(44, 82, 130)
pdf.set_text_color(255, 255, 255)
pdf.cell(60, 7, 'Indicator', align='L', fill=True)
pdf.cell(40, 7, 'Approximate Level', align='C', fill=True)
pdf.cell(0, 7, 'Historical Context', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

val_metrics = [
    ('Shiller CAPE Ratio', f'{shiller_cape:.1f}', 'Top 1% of 155-year history; near dot-com peak (~44)'),
    ('S&P 500 Forward P/E', '~22-23x', 'Lower than 2000 (~27x) but above long-term average (~16x)'),
    ('Top-10 Concentration', '~36-40%', 'Near/above dot-com peak (~27%), highest on record'),
    ('Tech Sector % of S&P', '~32%', 'Matches dot-com peak (~33%)'),
    ('CPI Inflation', '~3.0-3.5%', 'Sticky above 2% target; echoes 1970s and 2007'),
    ('Fed Funds Rate', '~4.25-4.50%', 'Rate-cut cycle begun; still restrictive vs. 2000/2007'),
]

fill = True
for indicator, level, context in val_metrics:
    pdf.set_fill_color(247, 250, 252) if fill else pdf.set_fill_color(255, 255, 255)
    pdf.set_text_color(51, 51, 51)
    pdf.set_font('Helvetica', '', 9)
    pdf.cell(60, 6, indicator, align='L', fill=fill)
    pdf.set_font('Helvetica', 'B', 9)
    pdf.cell(40, 6, level, align='C', fill=fill)
    pdf.set_font('Helvetica', '', 9)
    pdf.cell(0, 6, context, align='L', fill=fill, new_x='LMARGIN', new_y='NEXT')
    fill = not fill

pdf.ln(5)

# Historical Parallels
pdf.chapter_title('Key Historical Parallels')

# Dot-Com Section
pdf.section_title('1. The 1999-2000 Dot-Com Bubble [HIGH SIMILARITY]')

pdf.set_font('Helvetica', 'B', 9)
pdf.set_fill_color(44, 82, 130)
pdf.set_text_color(255, 255, 255)
pdf.cell(50, 7, 'Metric', align='L', fill=True)
pdf.cell(35, 7, 'March 2000', align='C', fill=True)
pdf.cell(0, 7, 'August 2026', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_text_color(51, 51, 51)
pdf.set_fill_color(247, 250, 252)
pdf.set_font('Helvetica', '', 9)
pdf.cell(50, 6, 'S&P 500 Forward P/E', align='L', fill=True)
pdf.cell(35, 6, '27x', align='C', fill=True)
pdf.cell(0, 6, '22-23x', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(255, 255, 255)
pdf.cell(50, 6, 'Top-10 Concentration', align='L', fill=False)
pdf.cell(35, 6, '27%', align='C', fill=False)
pdf.set_text_color(229, 62, 62)
pdf.cell(0, 6, '36-40% (+50% vs 2000)', align='L', fill=False, new_x='LMARGIN', new_y='NEXT')
pdf.set_text_color(51, 51, 51)

pdf.set_fill_color(247, 250, 252)
pdf.cell(50, 6, 'CAPE Ratio', align='L', fill=True)
pdf.cell(35, 6, '44.19 (peak)', align='C', fill=True)
pdf.cell(0, 6, f'{shiller_cape:.1f}', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(255, 255, 255)
pdf.cell(50, 6, '10-Year Treasury', align='L', fill=False)
pdf.cell(35, 6, '6.0%', align='C', fill=False)
pdf.cell(0, 6, f'{tnx:.2f}%', align='L', fill=False, new_x='LMARGIN', new_y='NEXT')

pdf.ln(3)
pdf.set_fill_color(235, 248, 255)
pdf.set_font('Helvetica', '', 10)
pdf.multi_cell(0, 6, 'Key Rhyme Pattern: Extreme valuation, record concentration, and tech dominance mirror the dot-com era. The critical difference: today\'s AI leaders are actually profitable, with NVIDIA generating substantial free cash flow vs. revenue-less startups in 1999. The question remains whether $600B+ annual hyperscaler capex can generate proportional returns.', fill=True)
pdf.ln(5)

# 2007 Section
pdf.add_page()
pdf.section_title('2. May 2007 Pre-Financial Crisis [HIGH SIMILARITY]')
pdf.body_text('Macro conditions in 2026 show eerie similarities to May 2007:')

pdf.set_font('Helvetica', 'B', 9)
pdf.set_fill_color(44, 82, 130)
pdf.set_text_color(255, 255, 255)
pdf.cell(40, 7, 'Factor', align='L', fill=True)
pdf.cell(35, 7, 'May 2007', align='C', fill=True)
pdf.cell(0, 7, 'August 2026', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_text_color(51, 51, 51)
pdf.set_fill_color(247, 250, 252)
pdf.set_font('Helvetica', '', 9)
pdf.cell(40, 6, 'Inflation', align='L', fill=True)
pdf.cell(35, 6, 'Sticky', align='C', fill=True)
pdf.cell(0, 6, 'CPI ~3.0-3.5% - sticky above target', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(255, 255, 255)
pdf.cell(40, 6, 'Oil Prices', align='L', fill=False)
pdf.cell(35, 6, 'Rising', align='C', fill=False)
pdf.cell(0, 6, 'Elevated / geopolitical risk premium', align='L', fill=False, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(247, 250, 252)
pdf.cell(40, 6, 'Unemployment', align='L', fill=True)
pdf.cell(35, 6, 'Low/stable', align='C', fill=True)
pdf.cell(0, 6, 'Still low but cooling', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(255, 255, 255)
pdf.cell(40, 6, 'Consumer Sentiment', align='L', fill=False)
pdf.cell(35, 6, 'Slipping', align='C', fill=False)
pdf.cell(0, 6, 'Soft relative to market highs', align='L', fill=False, new_x='LMARGIN', new_y='NEXT')

pdf.set_fill_color(247, 250, 252)
pdf.cell(40, 6, 'Market Leadership', align='L', fill=True)
pdf.cell(35, 6, 'Tech strong', align='C', fill=True)
pdf.cell(0, 6, 'Mag 7 / AI leaders dominant', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

pdf.ln(3)
pdf.set_fill_color(255, 245, 245)
pdf.set_text_color(229, 62, 62)
pdf.set_font('Helvetica', '', 10)
pdf.multi_cell(0, 6, 'Cautionary Note: In May 2007, the S&P broke above its dot-com high, earnings were strong, volatility low, credit spreads tight, and the bull narrative felt unstoppable. Yet subprime cracks were already showing. History may not repeat, but it rhymes.', fill=True)
pdf.set_text_color(51, 51, 51)
pdf.ln(5)

# 1960s-70s Section
pdf.section_title('3. The 1960s-70s: Geopolitics & Trade Wars [MEDIUM SIMILARITY]')
pdf.body_text('A structural shift toward a 1960s-70s-style regime appears underway:')
pdf.body_text('- Geopolitics dominant: Great-power competition and deglobalization pressures')
pdf.body_text('- Reshoring movement: CHIPS Act, tariffs, and supply-chain realignment')
pdf.body_text('- Fiscal dominance: Large deficits and rising debt-to-GDP')
pdf.body_text('- Inflation questions: Transitory vs. structural debate continues')
pdf.ln(3)

# The Rhyme Patterns
pdf.chapter_title('The Rhyme Patterns')

pdf.section_title('Pattern 1: Valuation Extremes [CRITICAL]')
pdf.body_text(f'The Shiller CAPE near {shiller_cape:.1f} has only been exceeded once (March 2000). Historically, starting CAPE levels above 35 have produced subpar real returns over the following decade.')

pdf.section_title('Pattern 2: Concentration Risk [CRITICAL]')
pdf.body_text('The top 10 stocks represent roughly 36-40% of the S&P 500 - among the highest levels on record. The market\'s fate rests on an unusually small number of companies.')

pdf.section_title('Pattern 3: Capex Intensity [WATCH]')
pdf.body_text('Hyperscaler AI capex is running at hundreds of billions annually. The question is not whether AI is real, but whether the infrastructure spending will generate proportional returns.')

pdf.section_title('Pattern 4: Macro Fragility [WATCH]')
pdf.body_text('Sticky inflation, elevated oil, softening labor data, and a disconnect between market highs and consumer sentiment create a familiar pre-crisis macro setup.')

# Historical Outcomes
pdf.add_page()
pdf.chapter_title('Historical Outcomes to Consider')

pdf.set_font('Helvetica', 'B', 9)
pdf.set_fill_color(44, 82, 130)
pdf.set_text_color(255, 255, 255)
pdf.cell(50, 7, 'Parallel', align='L', fill=True)
pdf.cell(55, 7, 'Historical Outcome', align='C', fill=True)
pdf.cell(0, 7, 'Timeline', align='L', fill=True, new_x='LMARGIN', new_y='NEXT')

outcomes = [
    ('Dot-Com Peak (Mar 2000)', 'Nasdaq -78%, S&P -49%', '2.5 years to bottom'),
    ('May 2007 Peak', 'S&P -57% during GFC', '17 months to bottom'),
    ('1960s-70s Regime', 'Stagflation, lost decade', '10+ years sideways'),
    ('1987 Black Monday', '-22% single day', 'Flash crash, quick recovery'),
]

fill = True
for parallel, outcome, timeline in outcomes:
    pdf.set_fill_color(247, 250, 252) if fill else pdf.set_fill_color(255, 255, 255)
    pdf.set_text_color(51, 51, 51)
    pdf.set_font('Helvetica', '', 9)
    pdf.cell(50, 7, parallel, align='L', fill=fill)
    pdf.set_text_color(229, 62, 62)
    pdf.cell(55, 7, outcome, align='C', fill=fill)
    pdf.set_text_color(51, 51, 51)
    pdf.cell(0, 7, timeline, align='L', fill=fill, new_x='LMARGIN', new_y='NEXT')
    fill = not fill

pdf.ln(5)

# Key Differences
pdf.chapter_title('Key Differences from Past Cycles')
pdf.set_fill_color(235, 248, 255)
pdf.set_font('Helvetica', '', 10)
pdf.multi_cell(0, 6, 'Why This Time Might Be Different (Bull Case): AI companies are actually profitable - unlike dot-com era. Lower forward P/E than 2000. Cooler IPO market. More disciplined hyperscaler balance sheets. Fed has more room to cut rates than in 2000 or 2007.', fill=True)
pdf.ln(5)

# Risk Summary
pdf.set_fill_color(255, 245, 245)
pdf.set_text_color(229, 62, 62)
pdf.set_font('Helvetica', 'B', 10)
pdf.cell(0, 6, 'Primary Risks:', new_x='LMARGIN', new_y='NEXT', align='L')
pdf.set_font('Helvetica', '', 10)
pdf.multi_cell(0, 6, '1. Valuation Crash: CAPE at historic extremes suggests limited upside, significant downside. 2. Concentration Cascade: If Mag7/AI leaders falter, broad market follows. 3. Capex Cliff: Massive annual AI spend must generate returns. 4. Macro Unwind: 2007-style fragility with sticky inflation. 5. Geopolitical Shock: Trade-war and supply-chain disruptions.', fill=True)
pdf.set_text_color(51, 51, 51)
pdf.ln(5)

# Conclusion
pdf.add_page()
pdf.chapter_title('Conclusion')
pdf.body_text('Mark Twain\'s quote rings true: "History doesn\'t repeat itself, but it often rhymes." Current conditions show compelling parallels to three distinct historical periods:')

pdf.set_font('Helvetica', 'B', 10)
pdf.cell(0, 6, '1. Dot-Com Bubble (1999-2000):', new_x='LMARGIN', new_y='NEXT', align='L')
pdf.set_font('Helvetica', '', 10)
pdf.cell(0, 6, '   Extreme valuations, high concentration, tech dominance', new_x='LMARGIN', new_y='NEXT', align='L')
pdf.ln(2)

pdf.set_font('Helvetica', 'B', 10)
pdf.cell(0, 6, '2. Pre-GFC (2007):', new_x='LMARGIN', new_y='NEXT', align='L')
pdf.set_font('Helvetica', '', 10)
pdf.cell(0, 6, '   Complacent macro, soft data beneath market highs, cracks forming', new_x='LMARGIN', new_y='NEXT', align='L')
pdf.ln(2)

pdf.set_font('Helvetica', 'B', 10)
pdf.cell(0, 6, '3. 1960s-70s:', new_x='LMARGIN', new_y='NEXT', align='L')
pdf.set_font('Helvetica', '', 10)
pdf.cell(0, 6, '   Geopolitical trade wars, inflation questions, regime shift', new_x='LMARGIN', new_y='NEXT', align='L')
pdf.ln(5)

pdf.body_text('The unique element is that all three patterns are simultaneously present. History suggests caution is warranted. The resolution depends on whether AI can deliver returns commensurate with the investment - a question that cannot be answered until the infrastructure cycle produces measurable results.')

# Bottom Line
pdf.set_fill_color(235, 248, 255)
pdf.set_draw_color(66, 153, 225)
pdf.rect(10, pdf.get_y(), 190, 20, 'DF')
pdf.set_xy(12, pdf.get_y() + 2)
pdf.set_font('Helvetica', 'B', 10)
pdf.set_text_color(43, 108, 176)
pdf.cell(0, 6, 'Bottom Line:', 0, 1)
pdf.set_font('Helvetica', '', 10)
pdf.set_text_color(51, 51, 51)
pdf.multi_cell(186, 5, 'The market is expensive by historical standards. While this does not predict an imminent crash, it does suggest below-average returns ahead. The key question: Is AI the "new economy" of 2026, or the "radio stocks" of 1929? Time will tell.')

# Save PDF
output_path = os.path.join(output_dir, '2026-08-23_history_rhymes.pdf')
pdf.output(output_path)
print(f"\nPDF generated successfully: {output_path}")

# Also save market data JSON for reference
json_path = os.path.join(output_dir, '2026-08-23_history_rhymes_data.json')
with open(json_path, 'w') as f:
    json.dump(market_data, f, indent=2, default=str)
print(f"Market data saved: {json_path}")
