#!/usr/bin/env python3
"""History Rhymes report for September 3, 2026 - data through Sep 2 close + Sep 3 pre-market.
Market data: Yahoo Finance chart API (real, fetched this morning). News: Google News RSS.
Yield gotcha honored: ^TNX/^FVX/^IRX are RAW percent. ASCII-only text (fpdf2 Helvetica = latin-1).
"""
import os
from fpdf import FPDF

trading_date = "September 2, 2026"
report_date = "September 3, 2026 (pre-market)"
output_pdf = r'C:\Users\thadd\OneDrive\Desktop\Spocks Reports\history_rhymes\2026-09-03_history_rhymes.pdf'
os.makedirs(os.path.dirname(output_pdf), exist_ok=True)

class PDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(26, 54, 93)
        self.cell(0, 10, 'History Rhymes - Market Pattern Analysis', new_x='LMARGIN', new_y='NEXT', align='L')
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, 'Historical Parallels to Current Market Conditions', new_x='LMARGIN', new_y='NEXT', align='L')
        self.cell(0, 6, f'{report_date} (Data through {trading_date} close + overnight news)', new_x='LMARGIN', new_y='NEXT', align='L')
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def chapter_title(self, title):
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(44, 82, 130)
        self.cell(0, 10, title, new_x='LMARGIN', new_y='NEXT', align='L')
        self.ln(2)

    def section_title(self, title):
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(74, 85, 104)
        self.cell(0, 8, title, new_x='LMARGIN', new_y='NEXT', align='L')
        self.ln(1)

    def body_text(self, text):
        self.set_font('Helvetica', '', 10)
        self.set_text_color(51, 51, 51)
        self.multi_cell(0, 6, text)
        self.ln(3)

    def callout(self, text, fill=(235, 248, 255), color=(51, 51, 51)):
        self.set_fill_color(*fill)
        self.set_font('Helvetica', '', 10)
        self.set_text_color(*color)
        self.multi_cell(0, 6, text, fill=True)
        self.ln(3)

    def table_header(self, cols):
        self.set_font('Helvetica', 'B', 9)
        self.set_fill_color(44, 82, 130)
        self.set_text_color(255, 255, 255)
        for width, label, align in cols:
            self.cell(width, 7, label, align=align, fill=True)
        self.ln()

    def table_row(self, cells, fill, bold_cols=(), color=(51, 51, 51)):
        for i, (width, text, align) in enumerate(cells):
            self.set_font('Helvetica', 'B' if i in bold_cols else '', 9)
            self.set_text_color(*color)
            self.set_fill_color(247, 250, 252) if fill else self.set_fill_color(255, 255, 255)
            self.cell(width, 6, text, align=align, fill=fill)
        self.ln()

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by History Rhymes Agent | Not investment advice | Page {self.page_no()}', align='C')

pdf = PDF()
pdf.add_page()

# ============ EXECUTIVE SUMMARY ============
summary = (
    "Executive Summary: The squeeze tightened and the tape shrugged. Tuesday's risk-off gave way to a broad Wednesday bounce - "
    "S&P 500 +0.5% to 7,666, Russell 2000 +1.1%, tech flat with NVDA +3.2% - as the global Treasury selloff paused (10Y flat at "
    "4.80%, TLT +0.1%). But the forces behind the regime call intensified overnight: WTI pushed to fresh six-week highs near "
    "$93-94 on renewed US-Iran exchanges around the Strait of Hormuz (Reuters, Sep 3), gold surged +2.7% to $4,484 (+24.8% y/y), "
    "and hike expectations escalated again - after Barclays' two, a top bank now sees THREE Fed hikes this year (Business Insider, "
    "Sep 2). The divergence that matters: equities are rallying the outcome they want (de-escalation) while oil and gold price the "
    "outcome they fear (escalation) - in 1990, relief rallies inside the Gulf-shock drawdown came with oil flat-to-lower, not "
    "making new highs. Layer on Friday's August payrolls (July printed -23K) and CPI holding at 3.4% with war effects showing in "
    "prices (NYT), and the setup remains a stagflationary squeeze at top-1% valuations. The rhymes that matter: 1979-80 (new "
    "hawkish chair + oil shock + parabolic gold), 1990 (bouncing inside the drawdown before the real bottom), and 1999-2000 "
    "(rotation out of tech while a Fed hikes into a bubble). VIX at 15.35 with oil at $93 is the 1987 signature: complacency "
    "under bond stress."
)
pdf.callout(summary, fill=(235, 248, 255))

# ============ HEADLINES ============
pdf.chapter_title('Top Headlines (Sep 1 - Sep 3)')
headlines = [
    ('"Wall Street rises as tech stocks climb and oil prices, bond yields hold relatively steady"', 'AP News, Sep 2'),
    ('"Bond selloff deepens as oil prices and public debt fears jolt markets"', 'Reuters/Yahoo, Sep 2'),
    ('"Treasury Selloff Pauses While Wall Street Stocks Rise, Oil price at $94"', 'Eurasia Business, Sep 2'),
    ('"Oil prices hit fresh 6-week highs on renewed Middle East tensions"', 'Reuters, Sep 3'),
    ('"Brent and WTI Retreat as Markets Monitor Strait of Hormuz Crude Flows"', 'Yahoo Finance UK, Sep 3'),
    ('"Oil prices surge after U.S. renews Iran strikes, heightening inflation fears"', 'NBC News, Sep 1'),
    ('"A top bank now sees 3 Fed rate hikes on the way. Here is what that means for stocks."', 'Business Insider, Sep 2'),
    ('"Barclays sees two more Fed rate hikes this year after Warsh speech"', 'Reuters, Aug 31'),
    ('"Global bonds sell off as Middle East conflict escalates, stoking inflation fears"', 'CNN, Sep 1'),
    ('"US Jobs Report Preview: Can August Payrolls Keep a September Fed Rate Hike Alive?"', 'markets.com, Aug 30'),
    ('"Inflation Surges as Effects of the Iran War Show in Prices"', 'NYT, Aug 24'),
    ('"Ray Dalio sees the classic signs of a bubble with AI, market looks like run-up to 1929 or 2000"', 'Yahoo Finance, Aug 14'),
]
pdf.table_header([(0, 'Headline', 'L'), (42, 'Source', 'L')])
fill = True
for title, src in headlines:
    pdf.table_row([(0, title, 'L'), (42, src, 'L')], fill)
    fill = not fill
pdf.ln(4)

# ============ SNAPSHOT ============
pdf.chapter_title('Current Market Snapshot (Sep 2 close; WTI/Gold/BTC/USD/VIX pre-market Sep 3)')
rows = [
    ('S&P 500', '7,666.60', '+0.5%', '+1.5%', '+19.5%', '+7.6%'),
    ('Nasdaq', '26,217.83', '+0.5%', '-2.4%', '+23.2%', '+7.7%'),
    ('Dow Jones', '53,061.95', '+0.6%', '+4.7%', '+17.2%', '+6.6%'),
    ('Russell 2000', '2,953.17', '+1.1%', '+2.1%', '+25.6%', '+8.0%'),
    ('10Y Yield', '4.80%', 'flat', '+31 bps', '+52 bps', '+10.3%'),
    ('5Y Yield', '4.55%', '-5 bps', '+34 bps', '+81 bps', '+14.1%'),
    ('13W T-Bill', '3.77%', 'flat', '+15 bps', '-26 bps', '+3.9%'),
    ('VIX', '15.35', '+1.0%', '-0.3%', '-6.1%', '-16.3%'),
    ('USD Index', '99.14', '-0.4%', '-0.3%', '+1.0%', 'flat'),
    ('WTI Crude', '92.95', '+2.1%', '-0.1%', '+45.3%', '+18.2%'),
    ('Gold', '4,484.30', '+2.7%', '+0.2%', '+24.8%', '-0.8%'),
    ('Bitcoin', '77,892', '+0.8%', '+22.1%', '-30.3%', '+12.0%'),
]
pdf.table_header([(40, 'Metric', 'L'), (30, 'Level', 'C'), (26, '1-Day', 'C'), (28, '3-Month', 'C'), (28, '1-Year', 'C'), (0, 'vs 200DMA', 'C')])
fill = True
for r in rows:
    pdf.table_row([(40, r[0], 'L'), (30, r[1], 'C'), (26, r[2], 'C'), (28, r[3], 'C'), (28, r[4], 'C'), (0, r[5], 'C')], fill, bold_cols=(1,))
    fill = not fill
pdf.ln(3)
pdf.set_font('Helvetica', 'I', 9)
pdf.set_text_color(100, 100, 100)
pdf.multi_cell(0, 5, 'Yields are raw percent (10Y = 4.80%); bps changes derived from raw yields. 1-month moves: WTI +22.7%, gold +9.5%, BTC +21.6% vs Nasdaq +1.2%. '
                     'Sep 2 sector tape: broad bounce - KRE +2.2%, Materials +1.7%, Health +0.8%, Financials +0.8%, Energy +0.5%, Tech flat (XLK -0.02%); TLT +0.1%, HYG flat. '
                     'Mega caps: NVDA +3.2%, META +2.5%, MSFT -0.8%. Credit tell: HYG sits -1.3% BELOW its 200-day while the S&P is +7.6% above - high-yield quietly disagreeing with equities. '
                     'Rotation intact: 3m leaders Health +17.2% / Financials +13.4% / Energy +10.9% vs Tech -6.4%; GOOGL -9.7% and AMZN -10.2% in a month; META -19.4% y/y below its 200-day; TSLA -15.7% 3m.')
pdf.ln(4)

# ============ REGIME READ ============
pdf.add_page()
pdf.section_title('The Regime Read: The Squeeze Tightens While the Tape Shrugs')
pdf.body_text(
    'Four forces are pulling at once, and one got stronger. (1) Supply shock escalating: WTI $92.95 (+2.1% today, +22.7% in a '
    'month, +45% y/y) at fresh six-week highs on renewed Hormuz strikes - energy (+43.8% y/y) remains the best major sector. '
    '(2) Policy bind tightening: hike expectations upgraded from two (Barclays, Aug 31) to three (top bank, Sep 2); August CPI '
    'due ~Sep 11 will carry war-oil pass-through, with the NYT already reporting inflation surging from the Iran war. (3) Bond '
    'revolt paused, not over: the 10Y is flat at 4.80% after the global selloff, the long-end-led steepening (10Y-3M ~ +103 bps) '
    'is still a vigilante structure, not a growth scare - and HYG below its 200-day says credit never bought the bounce. '
    '(4) Valuations: CAPE ~41-42 (top 1% of 155 years), record top-10 concentration, forward P/E ~22-23x. Breadth is the tell: '
    '3-month leadership is health (+17.2%), financials (+13.4%), energy (+10.9%), equal-weight (+4.5%) while tech lags (-6.4%) '
    'and the Nasdaq is -2.4% over 3 months against an index near highs - either healthy 1990/1991-style re-broadening or the '
    'late-1999 pre-peak rotation. Mega-cap internals argue stress: META and TSLA below their 200-days, GOOGL and AMZN down ~10% '
    'in a month. The Fed and oil decide which rhyme wins.'
)

# ============ HISTORICAL PARALLELS ============
pdf.add_page()
pdf.chapter_title('Historical Parallels - Ranked by Fit')

def parallel(title, fit, then_text, now_text, outcome_text, watch_text):
    pdf.section_title(f'{title}  [fit: {fit}/5]')
    pdf.body_text('Then: ' + then_text)
    pdf.body_text('Now: ' + now_text)
    pdf.body_text('What happened next: ' + outcome_text)
    pdf.body_text('Confirm/break: ' + watch_text)
    pdf.ln(2)

parallel('1. 1979-1980 - The Volcker Inflation Fight', 4,
    'A brand-new Fed chair (Volcker, Aug 1979) inherits stubborn inflation just as the Iranian revolution doubles oil. Bonds are '
    'in open revolt, gold goes parabolic, and the Fed chooses inflation-fighting over growth. Stocks chop violently (-10% to -15% '
    'drawdowns in 1980) inside a wide, treacherous range; two recessions follow before the 1982 bottom.',
    'A brand-new Fed chair (Warsh) pivots hawkish at Jackson Hole; hike expectations escalated again Wednesday (top bank: three '
    'more hikes; Barclays: two); oil at six-week highs on Hormuz strikes; gold $4,484 (+2.7% today, +24.8% y/y, +9.5% 1m) is doing '
    'what gold did in 1979 - while stocks sit at top-1% valuations, unlike 1979.',
    'Nominal 12-month returns around the first Volcker hikes were roughly flat to -10%, but real returns were deeply negative; the '
    'real pain extended until oil collapsed and policy flipped in 1982.',
    'CONFIRM if FOMC hikes Sep 16, 10Y breaks 5%, WTI holds above $100. BREAK if Iran de-escalates, WTI back under $80, Fed holds.')

parallel('2. 1990 - Gulf War Oil Shock', 3.5,
    'Iraq invades Kuwait (Aug 2, 1990); oil doubles from $17 toward $40; the S&P 500 falls ~20% in ten weeks - but not in a '
    'straight line: violent 4-6% counter-rallies punctuated the drawdown. The bottom (Oct 11, 1990) came BEFORE the war was won; '
    'once the outcome stopped being ambiguous, oil mean-reverted and a decade-long bull began.',
    'US-Iran exchanges around Hormuz with crude +22.7% in a month. Tuesday\'s -1% gave way to Wednesday\'s +0.5% bounce on a bond '
    'pause - the shape of a counter-rally inside a drawdown, not necessarily its resolution. The tell: oil made NEW six-week highs '
    'during the bounce. In 1990, relief rallies came with oil flat-to-lower. VIX 15.35 still prices disruption, not closure.',
    'Peak-to-trough -20%, then a V-shaped recovery once de-escalation was clear; the uncertainty premium unwound within months. '
    'Twelve months from the invasion start, the index was roughly flat.',
    'CONFIRM if WTI pushes through $100 or shipping insurance spikes. BREAK via de-escalation/headline fade with oil under $80 - '
    'the base case that ended 1990\'s drawdown.')

parallel('3. 1999-2000 - Hiking Into a Bubble', 4,
    'The Fed hiked 175 bps (Jun 1999-May 2000) straight into a CAPE-44 bubble. The internal rotation came first: leadership '
    'shifted to value, energy and small caps in late 1999 while the index made highs - breadth left before price did. The Nasdaq '
    'made its final +24% sprint into March 2000, then fell 78% over 2.5 years.',
    'CAPE ~41-42 (only Mar 2000 was higher), record top-10 concentration, forward P/E ~22-23x, and a Fed now priced for up to '
    'three hikes. The 3-month tape rhymes with late-1999: health +17.2%, financials +13.4%, energy +10.9%, RSP +4.5% leading '
    'while tech (-6.4%) and the Nasdaq (-2.4%) lag an index near highs; GOOGL/AMZN ~-10% in a month.',
    'From comparable valuation-plus-tightening setups, 12-month forwards were -10% to -20%; the 2000-02 unwind ultimately took the '
    'S&P -49% over 30 months.',
    'CONFIRM if the Fed hikes into negative payrolls (2000\'s kill shot was tightening biting a slowing economy). BREAK if the '
    'Fed pauses with oil calming - the 1995 soft-landing repeat.')

parallel('4. 1973-74 - The Stagflation Bear', 3.5,
    'OPEC embargo + accelerating CPI + a Fed hiking into weakness. The S&P fell ~48% from Jan 1973 to Oct 1974. Energy was the '
    'only winning sector; every P/E compression was real. The fingerprint: negative payrolls, above-target inflation, hawkish '
    'central bank, and energy leadership - all simultaneously.',
    'July payrolls -23K (first negative print of the cycle), CPI 3.4% with war effects showing in prices (NYT), a Fed threatening '
    'up to three hikes, and energy +43.8% y/y leading all sectors. Discretionary (XLY -1.6% 3m, -0.1% y/y) already behaves like '
    '1974\'s consumer.',
    'Twelve-month forwards from stagflation fingerprints were the worst of the modern era (median -20% to -30%); the lesson is '
    'that multiple compression and earnings decline compound when the Fed cannot ease.',
    'CONFIRM with a second negative payrolls print (Fri) plus a September hike. BREAK if CPI decelerates below 3% and the Fed '
    'stays on hold.')

parallel('5. 1987 - The Bond-Vigilante Trigger', 3,
    'The 10-year climbed ~300 bps through 1987 while stocks made new highs; the crash came WITH the bond market breaking - equities '
    'were the release valve for a disorderly bond repricing. Fiscal deficits and a falling dollar were the backdrop.',
    'A global bond selloff on inflation-plus-debt fears paused but intact (10Y 4.80%), equities +7.6% above the 200-day near '
    'highs, and the long-end-led steepening is the same vigilante mechanism. The 1987 signature is here: VIX 15.35 - below its '
    '1-year average - with oil at $93 and yields near cycle highs, i.e., complacency under stress. Differences: the dollar is '
    'stable (99.1) versus 1987\'s slide, and no portfolio-insurance analog is known today.',
    '1987 was -34% in weeks, but only -9% for the full year, with the bull resuming by 1989 - a violent repricing, not a lost '
    'decade.',
    'CONFIRM if 10Y breaks 5% while VIX stays sub-20. BREAK on bond yields stabilizing without a Fed rescue.')

pdf.ln(2)
pdf.section_title('Carry-over Parallel: 1965-66 "Go-Go Years" (May 2026 top-scored fit 4.5/5)')
pdf.body_text(
    'Tight labor, sticky inflation, a Fed behind the curve, fiscal pressure and a long-yield breakout - all still in place and now '
    'compounded by an oil shock and bubble valuations. Composite base rate from that synthesis: median 12-month return -5% to -15%, '
    'max drawdown -17% to -25%. That remains the central scenario band around this report.'
)

# ============ SCORECARD ============
pdf.add_page()
pdf.chapter_title('Parallel Scorecard')
score_rows = [
    ('1979-80 Volcker fight', 'High (new hawk + oil)', 'Low (stocks were cheap)', 'Extreme', 'Flat to -10% nominal', '4.0'),
    ('1990 Gulf War shock', 'Medium', 'Medium', 'High', '~Flat; -20% drawdown first', '3.5'),
    ('1999-2000 hike into bubble', 'Medium (hiking Fed)', 'Extreme', 'Low', '-10% to -20% (then -49%)', '4.0'),
    ('1973-74 stagflation bear', 'High', 'Medium', 'High', '-20% to -30%', '3.5'),
    ('1987 vigilante trigger', 'Medium', 'High', 'Medium', '-34% fast; flat year', '3.0'),
    ('1965-66 go-go peak', 'High', 'High', 'Low', '-5% to -15%', '4.0'),
]
pdf.table_header([(38, 'Parallel', 'L'), (30, 'Macro Match', 'L'), (30, 'Valuation Match', 'L'), (22, 'Oil Match', 'C'), (46, '12m Outcome Then', 'L'), (14, 'Fit', 'C')])
fill = True
for r in score_rows:
    pdf.table_row([(38, r[0], 'L'), (30, r[1], 'L'), (30, r[2], 'L'), (22, r[3], 'C'), (46, r[4], 'L'), (14, r[5], 'C')], fill, bold_cols=(5,))
    fill = not fill
pdf.ln(4)

pdf.section_title('Base-Rate Implications')
pdf.body_text(
    'Weighted across the analog family, the distribution still skews negative over 6-12 months: median 12-month return roughly '
    '-5% to -15%, with tail cases (oil above $100 sustained AND a September hike) reaching -20% to -30%. The bull case is the '
    '1990 resolution: de-escalation, oil back toward $80, bond yields stabilize, and the re-broadening already visible in '
    'RSP/health/financials becomes a genuine 1991-style re-risking. What changed in the last 24 hours: the equity bounce is '
    'consistent with both resolutions, but oil making NEW six-week highs during the bounce is not - that divergence has to close '
    'in one direction. What tips the tape from rhyme to repeat: (a) FOMC delivers a hike Sep 16 while payrolls are negative; '
    '(b) 10Y breaks 5.0% with HYG under its 200-day (it already is, -1.3%); (c) WTI holds above $100; (d) the S&P loses its '
    '200-day (currently +7.6% above). Two quieter flags: Bitcoin\'s +21.6% one-month rebound has neutralized the crypto-leads-down '
    'warning for now - watch whether it rolls over again; and gold\'s +2.7% surge through $4,400 while the 10Y sits bid-less at '
    '4.80% is the 1979-80 haven signature intensifying, not fading. VIX at 15.35 with oil at $93 is the 1987 complacency '
    'signature: the tape is not priced for the regime it is in.'
)

pdf.section_title('Watch Calendar')
watch = [
    ('Thu Sep 3', 'Weekly jobless claims (8:30 ET) - second labor read of the week; also settles the open Sep 3 <210K NO claims position'),
    ('Fri Sep 4', 'August jobs report (8:30 ET) - the week\'s fulcrum; second negative print + live hike odds = stagflation confirm'),
    ('~Sep 11', 'August CPI - does the war-oil spike show up at the pump/CPI line (NYT already reports war effects in prices)'),
    ('Sep 15-16', 'FOMC decision - hike vs hold is the regime decider; pricing now ranges from hold to three hikes'),
    ('Continuous', 'Hormuz escalation headlines; WTI $93/$100; 10Y 4.80%/5.00%; VIX 15/20/25 ladder; gold $4,500; HYG vs 200-day'),
]
pdf.table_header([(24, 'When', 'L'), (0, 'What and why', 'L')])
fill = True
for w, why in watch:
    pdf.table_row([(24, w, 'L'), (0, why, 'L')], fill)
    fill = not fill
pdf.ln(4)

pdf.set_font('Helvetica', 'I', 9)
pdf.set_text_color(100, 100, 100)
pdf.multi_cell(0, 5, 'Methodology note: Market data from Yahoo Finance chart API, Sep 2, 2026 close (VIX, USD, WTI, gold, BTC as of Sep 3 pre-market). '
                     'Headlines via Google News RSS (AP, Reuters, CNN, NBC, NYT, Business Insider, Eurasia Business News, markets.com, Yahoo Finance). Yields reported as raw percent '
                     '(10Y = 4.80%); bps changes derived from raw yields. Historical parallels are analogies for base-rate reasoning, not predictions. '
                     'This report is not investment advice.')

pdf.output(output_pdf)
print(f"PDF written: {output_pdf}")
print(f"Size: {os.path.getsize(output_pdf)} bytes, pages: {pdf.page_no()}")