#!/usr/bin/env python3
"""History Rhymes report for September 2, 2026 - data through Sep 1 close + Sep 2 pre-market.
Market data: Yahoo Finance chart API (real, fetched this morning). News: Google News RSS.
Yield gotcha honored: ^TNX/^FVX/^IRX are RAW percent. ASCII-only text (fpdf2 Helvetica = latin-1).
"""
import os
from fpdf import FPDF

trading_date = "September 1, 2026"
report_date = "September 2, 2026 (pre-market)"
output_pdf = r'C:\Users\thadd\OneDrive\Desktop\Spocks Reports\history_rhymes\2026-09-02_history_rhymes.pdf'
os.makedirs(os.path.dirname(output_pdf), exist_ok=True)

class PDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(26, 54, 93)
        self.cell(0, 10, 'History Rhymes - Market Pattern Analysis', new_x='LMARGIN', new_y='NEXT', align='L')
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, 'Historical Parallels to Current Market Conditions', new_x='LMARGIN', new_y='NEXT', align='L')
        self.cell(0, 6, f'{report_date} (Data through {trading_date} close + overnight news)', new_x='LMARGIN', new_y='NEXT', align='L')
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def chapter_title(self, title):
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(44, 82, 130)
        self.cell(0, 10, title, new_x='LMARGIN', new_y='NEXT', align='L')
        self.ln(2)

    def section_title(self, title):
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(74, 85, 104)
        self.cell(0, 8, title, new_x='LMARGIN', new_y='NEXT', align='L')
        self.ln(1)

    def body_text(self, text):
        self.set_font('Helvetica', '', 10)
        self.set_text_color(51, 51, 51)
        self.multi_cell(0, 6, text)
        self.ln(3)

    def callout(self, text, fill=(235, 248, 255), color=(51, 51, 51)):
        self.set_fill_color(*fill)
        self.set_font('Helvetica', '', 10)
        self.set_text_color(*color)
        self.multi_cell(0, 6, text, fill=True)
        self.ln(3)

    def table_header(self, cols):
        self.set_font('Helvetica', 'B', 9)
        self.set_fill_color(44, 82, 130)
        self.set_text_color(255, 255, 255)
        for width, label, align in cols:
            self.cell(width, 7, label, align=align, fill=True)
        self.ln()

    def table_row(self, cells, fill, bold_cols=(), color=(51, 51, 51)):
        for i, (width, text, align) in enumerate(cells):
            self.set_font('Helvetica', 'B' if i in bold_cols else '', 9)
            self.set_text_color(*color)
            self.set_fill_color(247, 250, 252) if fill else self.set_fill_color(255, 255, 255)
            self.cell(width, 6, text, align=align, fill=fill)
        self.ln()

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by History Rhymes Agent | Not investment advice | Page {self.page_no()}', align='C')

pdf = PDF()
pdf.add_page()

# ============ EXECUTIVE SUMMARY ============
summary = (
    "Executive Summary: The regime call got louder overnight. The United States and Iran resumed military exchanges around the "
    "Strait of Hormuz - the chokepoint for roughly a fifth of the world's seaborne oil - and WTI briefly printed above $90 before "
    "settling near $90 on September 1, up about 11% in a month. The oil shock is now leaking into the one market that forces "
    "everyone's hand: bonds. A global bond selloff deepened into Wednesday on 'oil prices and public debt fears' (Reuters), pushing "
    "the U.S. 10-year to 4.80% while equities slid (S&P 500 -0.7%, Nasdaq -1.0%, Russell 2000 -1.2%). Layer on the policy bind - "
    "Fed Chair Kevin Warsh's hawkish Jackson Hole turn has markets pricing a possible September HIKE (Barclays sees two more hikes "
    "this year) even as July payrolls printed negative (-23K) and CPI holds at 3.4% - and the setup is a textbook stagflationary "
    "squeeze at record valuations. The rhymes that matter now: 1979-80 (new hawkish chair + oil shock + bond revolt), 1990 (Gulf "
    "military action + oil spike + confidence shock), and 1999-2000 (hiking into a top-1% valuation bubble). The swing variable is "
    "oil: 1990 ended in a V-recovery when the conflict de-escalated; 1979-80 ended in a double recession when it did not."
)
pdf.callout(summary, fill=(235, 248, 255))

# ============ HEADLINES ============
pdf.chapter_title('Top Headlines (Aug 31 - Sep 2)')
headlines = [
    ('"Bond selloff deepens as oil prices and public debt fears jolt markets"', 'Reuters, Sep 2'),
    ('"Global bonds sell off as Middle East conflict escalates, further stoking inflation fears"', 'CNN, Sep 1'),
    ('"U.S. crude oil hits $90 per barrel following latest U.S. attacks against Iran"', 'CNBC, Sep 1'),
    ('"Oil settles up by more than 2.5% as US and Iran resume military attacks"', 'Reuters, Aug 31'),
    ('"Oil prices rise and stocks fall after US hits Iranian sites in the Strait of Hormuz"', 'AP News, Aug 31'),
    ('"Markets see Warsh endorsing a rate hike in September. Not everyone is convinced"', 'CNBC, Aug 31'),
    ('"Barclays sees two more Fed rate hikes this year after Warsh speech"', 'Reuters, Aug 31'),
    ('"Jackson Hole analyst roundup: hike chances higher, may put Fed \'at odds\' with Treasury"', 'CNBC, Aug 31'),
    ('"ADP Employment Report set to confirm that US job creation has lost steam"', 'FXStreet, Sep 2'),
    ('"Employment Report: 23K Jobs Shed in July, Worse Than Expected"', 'Advisor Perspectives, Aug 7'),
    ('"Stocks Haven\'t Been This Expensive Since the Dot-Com Boom"', 'Inc.com, Aug 17'),
    ('"Ray Dalio on the AI bubble nearing 1929, 2000 levels: \'wealth is not the same as money\'"', 'Fortune, Aug 4'),
]
pdf.table_header([(0, 'Headline', 'L'), (42, 'Source', 'L')])
fill = True
for title, src in headlines:
    pdf.table_row([(0, title, 'L'), (42, src, 'L')], fill)
    fill = not fill
pdf.ln(4)

# ============ SNAPSHOT ============
pdf.chapter_title('Current Market Snapshot (Sep 1 close; WTI/Gold/BTC pre-market Sep 2)')
rows = [
    ('S&P 500', '7,631.47', '-0.71%', '+0.3%', '+18.1%', '+7.2%'),
    ('Nasdaq', '26,099.77', '-1.03%', '-3.7%', '+21.7%', '+7.3%'),
    ('Dow Jones', '52,766.88', '-0.79%', '+2.8%', '+15.9%', '+6.1%'),
    ('Russell 2000', '2,920.13', '-1.23%', '-0.4%', '+23.4%', '+6.8%'),
    ('10Y Yield', '4.80%', '+4 bps', '+34 bps', '+57 bps', '+10.3%'),
    ('5Y Yield', '4.56%', '+5 bps', '+38 bps', '+87 bps', '+14.3%'),
    ('13W T-Bill', '3.77%', '+4 bps', '+16 bps', '-27 bps', '+3.9%'),
    ('VIX', '16.34', 'flat', '+1.7%', '-4.9%', '-11.1%'),
    ('USD Index', '99.78', '+0.1%', '+0.3%', '+1.4%', '+0.6%'),
    ('WTI Crude', '89.34', '-1.0%*', '+11.2%', '+36.2%', '+13.8%'),
    ('Gold', '4,372.30', '+0.6%', '-1.5%', '+23.2%', '-3.2%'),
    ('Bitcoin', '76,780', '-0.8%', '+19.9%', '-31.0%', '+10.5%'),
]
pdf.table_header([(40, 'Metric', 'L'), (30, 'Level', 'C'), (26, '1-Day', 'C'), (28, '3-Month', 'C'), (28, '1-Year', 'C'), (0, 'vs 200DMA', 'C')])
fill = True
for r in rows:
    pdf.table_row([(40, r[0], 'L'), (30, r[1], 'C'), (26, r[2], 'C'), (28, r[3], 'C'), (28, r[4], 'C'), (0, r[5], 'C')], fill, bold_cols=(1,))
    fill = not fill
pdf.ln(3)
pdf.set_font('Helvetica', 'I', 9)
pdf.set_text_color(100, 100, 100)
pdf.multi_cell(0, 5, 'Yields shown in bps change on a raw-percent basis (10Y = 4.80%). *WTI closed ~$90.2 on Sep 1 and eased to $89.3 pre-market after the $90+ spike. Sector tape on Sep 1: Energy +1.3% (1y +43.3%) and Health +0.7% (3m +17.3%) up on a down day; Tech -1.5% (3m -7.4%), Discretionary -1.7%, Industrials -1.4%, regionals (KRE) -1.3%, high-yield (HYG) -0.9%, TLT -0.8%. Mega caps: AAPL +2.6%, NVDA -1.5%, MSFT -1.2%, TSLA -3.2%, GOOGL -1.3%, AMZN -1.9%, META +1.1%.')
pdf.ln(4)

# ============ REGIME READ ============
pdf.section_title('The Regime Read: A Stagflationary Squeeze at Bubble Valuations')
pdf.body_text(
    'Four forces are pulling at once. (1) Supply shock: US-Iran strikes around Hormuz drove crude above $90 - energy is the best '
    'major sector over the past year (+43%) and the only one bid on a down day. (2) Policy bind: CPI 3.4% and rising oil give Warsh '
    'cover to HIKE into the weakest labor market of the cycle (July payrolls -23K; August NFP Friday). (3) Bond revolt: a global '
    'selloff driven by inflation-plus-debt fears, with the long end leading (10Y-3M spread +103 bps and re-steepening from the '
    'long end - the classic bond-vigilante signature, not a growth scare). (4) Valuations: CAPE ~41-42 (top 1% of 155 years), '
    'top-10 concentration at records, forward P/E ~22-23x. Markets have seen each force alone. The 1979-2000 composite - Volcker '
    'macro with dot-com multiples - is the rare, dangerous version. Breadth is the tell: the past 3 months rotated into equal-weight '
    '(RSP +3.6%), health care and staples while tech lagged (-7.4%) - either healthy 1990-style re-broadening, or the late-1999 '
    'pre-peak rotation. The Fed and oil decide which.'
)

# ============ HISTORICAL PARALLELS ============
pdf.add_page()
pdf.chapter_title('Historical Parallels - Ranked by Fit')

def parallel(title, fit, then_text, now_text, outcome_text, watch_text):
    pdf.section_title(f'{title}  [fit: {fit}/5]')
    pdf.body_text('Then: ' + then_text)
    pdf.body_text('Now: ' + now_text)
    pdf.body_text('What happened next: ' + outcome_text)
    pdf.body_text('Confirm/break: ' + watch_text)
    pdf.ln(2)

parallel('1. 1979-1980 - The Volcker Inflation Fight', 4,
    'A brand-new Fed chair (Volcker, Aug 1979) inherits stubborn inflation just as the Iranian revolution doubles oil. Bonds are '
    'in open revolt, gold goes parabolic, and the Fed chooses inflation-fighting over growth. Stocks chop violently (-10% to -15% '
    'drawdowns in 1980) inside a wide, treacherous range; two recessions follow before the 1982 bottom.',
    'A brand-new Fed chair (Warsh) pivots hawkish at Jackson Hole; hike odds surge (Barclays: two more hikes in 2026); oil shocks '
    'on Gulf escalation; the long end sells off on debt fear; gold (+23% y/y to $4,372) is doing what gold did in 1979 - only at a '
    'far higher starting valuation regime for stocks.',
    'Nominal 12-month returns around the first Volcker hikes were roughly flat to -10%, but real returns were deeply negative; the '
    'real pain extended until oil collapsed and policy flipped in 1982.',
    'CONFIRM if FOMC hikes Sep 16, 10Y breaks 5%, WTI holds above $100. BREAK if Iran de-escalates, WTI back under $80, Fed holds.')

parallel('2. 1990 - Gulf War Oil Shock', 3.5,
    'Iraq invades Kuwait (Aug 2, 1990); oil doubles from $17 toward $40; the S&P 500 falls ~20% in ten weeks; consumer confidence '
    'collapses; a mild recession follows. The bottom (Oct 11, 1990) came BEFORE the war was won - once the outcome stopped being '
    'ambiguous, oil mean-reverted and a decade-long bull began.',
    'US-Iran exchanges around Hormuz - a bigger chokepoint than Kuwait - with crude +11% in a month and a global risk premium '
    'building. VIX at 16 says the market is pricing disruption, not closure: 1990\'s initial selloff began from similar complacency.',
    'Peak-to-trough -20%, then a V-shaped recovery once de-escalation was clear; oil halved and the uncertainty premium unwound '
    'within months. Twelve months from the invasion start, the index was roughly flat.',
    'CONFIRM if WTI pushes through $100 or shipping insurance spikes. BREAK via de-escalation/headline fade - the base case that '
    'ended 1990\'s drawdown.')

parallel('3. 1999-2000 - Hiking Into a Bubble', 4,
    'The Fed hiked 175 bps (Jun 1999-May 2000) straight into a CAPE-44 bubble. The Nasdaq made its final +24% sprint into March '
    '2000, then fell 78% over 2.5 years. The internal rotation came first: leadership shifted to value, energy and small caps in '
    'late 1999 while the index made highs - breadth left before price did.',
    'CAPE ~41-42 (only Mar 2000 was higher), top-10 concentration at records, forward P/E ~22-23x, and a Fed signaling hikes. The '
    '3-month tape rhymes with late-1999: RSP/health/staples/staples leadership while tech (XLK -7.4% 3m) and Nasdaq (-3.7% 3m) lag '
    'an index near highs.',
    'From comparable valuation-plus-tightening setups, 12-month forwards were -10% to -20%; the 2000-02 unwind ultimately took the '
    'S&P -49% over 30 months.',
    'CONFIRM if the Fed hikes into negative payrolls (2000\'s kill shot was tightening biting a slowing economy). BREAK if the '
    'Fed pauses with oil calming - the 1995 soft-landing repeat.')

parallel('4. 1973-74 - The Stagflation Bear', 3.5,
    'OPEC embargo + accelerating CPI + a Fed hiking into weakness. The S&P fell ~48% from Jan 1973 to Oct 1974. Energy was the '
    'only winning sector; every P/E compression was real. The fingerprint: negative payrolls, above-target inflation, hawkish '
    'central bank, and energy leadership - all simultaneously.',
    'July payrolls -23K (first negative print of the cycle), CPI 3.4%, a Fed threatening hikes, and energy +43% y/y leading all '
    'sectors. Discretionary (-1.1% y/y) already behaves like 1974\'s consumer.',
    'Twelve-month forwards from stagflation fingerprints were the worst of the modern era (median -20% to -30%); the lesson is '
    'that multiple compression and earnings decline compound when the Fed cannot ease.',
    'CONFIRM with a second negative payrolls print (Fri) plus a September hike. BREAK if CPI decelerates below 3% and the Fed '
    'stays on hold.')

parallel('5. 1987 - The Bond-Vigilante Trigger', 3,
    'The 10-year climbed ~300 bps through 1987 while stocks made new highs; the crash came WITH the bond market breaking - equities '
    'were the release valve for a disorderly bond repricing. Fiscal deficits and a falling dollar were the backdrop.',
    'A global bond selloff on "inflation and public debt fears" (Reuters) with the US 10Y at 4.80% and equities still +7% above '
    'the 200-day near highs. The long-end-led steepening is the same vigilante mechanism. Key difference: the dollar is stable '
    '(99.8) versus 1987\'s slide, and there is no portfolio-insurance analog known today.',
    '1987 was -34% in weeks, but only -9% for the full year, with the bull resuming by 1989 - a violent repricing, not a lost decade.',
    'CONFIRM if 10Y breaks 5% while VIX stays sub-20 (complacency under stress is the 1987 signature). BREAK on bond yields '
    'stabilizing without a Fed rescue.')

pdf.ln(2)
pdf.section_title('Carry-over Parallel: 1965-66 "Go-Go Years" (May 2026 top-scored fit 4.5/5)')
pdf.body_text(
    'Tight labor, sticky inflation, a Fed behind the curve, fiscal pressure and a long-yield breakout - all still in place and now '
    'compounded by an oil shock and bubble valuations. Composite base rate from that synthesis: median 12-month return -5% to -15%, '
    'max drawdown -17% to -25%. That remains the central scenario band around this report.')

# ============ SCORECARD ============
pdf.add_page()
pdf.chapter_title('Parallel Scorecard')
score_rows = [
    ('1979-80 Volcker fight', 'High (new hawk + oil)', 'Low (stocks were cheap)', 'Extreme', 'Flat to -10% nominal', '4.0'),
    ('1990 Gulf War shock', 'Medium', 'Medium', 'High', '~Flat; -20% drawdown first', '3.5'),
    ('1999-2000 hike into bubble', 'Medium (hiking Fed)', 'Extreme', 'Low', '-10% to -20% (then -49%)', '4.0'),
    ('1973-74 stagflation bear', 'High', 'Medium', 'High', '-20% to -30%', '3.5'),
    ('1987 vigilante trigger', 'Medium', 'High', 'Medium', '-34% fast; flat year', '3.0'),
    ('1965-66 go-go peak', 'High', 'High', 'Low', '-5% to -15%', '4.0'),
]
pdf.table_header([(38, 'Parallel', 'L'), (30, 'Macro Match', 'L'), (30, 'Valuation Match', 'L'), (22, 'Oil Match', 'C'), (46, '12m Outcome Then', 'L'), (14, 'Fit', 'C')])
fill = True
for r in score_rows:
    pdf.table_row([(38, r[0], 'L'), (30, r[1], 'L'), (30, r[2], 'L'), (22, r[3], 'C'), (46, r[4], 'L'), (14, r[5], 'C')], fill, bold_cols=(5,))
    fill = not fill
pdf.ln(4)

pdf.section_title('Base-Rate Implications')
pdf.body_text(
    'Weighted across the analog family, the distribution skews negative over 6-12 months: median 12-month return roughly -5% to '
    '-15%, with tail cases (oil above $100 sustained AND a September hike) reaching -20% to -30%. The bull case is not dead - it '
    'is the 1990 resolution: de-escalation, oil back toward $80, bond yields stabilize, and the re-broadening already visible in '
    'RSP/health/staples becomes a genuine 1991-style re-risking. What tips the tape from rhyme to repeat: (a) FOMC delivers a hike '
    'Sep 16 while payrolls are negative; (b) 10Y breaks 5.0% with HYG breaking its 200-day; (c) WTI holds above $100; (d) the '
    'S&P loses its 200-day (currently +7.2% above). Two quieter flags worth respecting: Bitcoin is -31% y/y while equities are '
    '+18% - in 2021-22 crypto peaked first and led equities down by weeks; and gold\'s -2.9% liquidation dip on Sep 1 followed by '
    'an immediate bid is the 1979-80 pattern of a haven consolidating, not dying.')

pdf.section_title('Watch Calendar')
watch = [
    ('Wed Sep 2', 'ADP employment (8:15 ET) - first read on whether July\'s -23K was noise or trend'),
    ('Thu Sep 3', 'Weekly jobless claims (8:30 ET) - also settles the open Sep 3 <210K NO claims position'),
    ('Fri Sep 4', 'August jobs report (8:30 ET) - the week\'s fulcrum; second negative print + hike odds = stagflation confirm'),
    ('~Sep 11', 'August CPI - does the oil spike start showing up at the pump/CPI line'),
    ('Sep 15-16', 'FOMC decision - hike vs hold is the regime decider; watch the statement and dot path'),
    ('Continuous', 'Hormuz escalation headlines; WTI $90/$100; 10Y 4.80%/5.00%; VIX 16/20/25 ladder'),
]
pdf.table_header([(24, 'When', 'L'), (0, 'What and why', 'L')])
fill = True
for w, why in watch:
    pdf.table_row([(24, w, 'L'), (0, why, 'L')], fill)
    fill = not fill
pdf.ln(4)

pdf.set_font('Helvetica', 'I', 9)
pdf.set_text_color(100, 100, 100)
pdf.multi_cell(0, 5, 'Methodology note: Market data from Yahoo Finance chart API, Sep 1, 2026 close (WTI, gold, BTC as of Sep 2 pre-market). '
                     'Headlines via Google News RSS (Reuters, CNN, CNBC, AP, FXStreet, Fortune, Inc., Advisor Perspectives). Yields reported as raw percent '
                     '(10Y = 4.80%); bps changes derived from raw yields. Historical parallels are analogies for base-rate reasoning, not predictions. '
                     'This report is not investment advice.')

pdf.output(output_pdf)
print(f"PDF written: {output_pdf}")
print(f"Size: {os.path.getsize(output_pdf)} bytes, pages: {pdf.page_no()}")