#!/usr/bin/env python3
"""History Rhymes report for August 29, 2026 - data through Friday Aug 28 close."""

import os
from fpdf import FPDF

trading_date = "August 28, 2026"
report_date = "August 29, 2026"
output_dir = r'C:\Users\thadd\OneDrive\Desktop\Spocks Reports\history_rhymes'
os.makedirs(output_dir, exist_ok=True)

class PDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(26, 54, 93)
        self.cell(0, 10, 'History Rhymes - Market Pattern Analysis', new_x='LMARGIN', new_y='NEXT', align='L')
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, 'Historical Parallels to Current Market Conditions', new_x='LMARGIN', new_y='NEXT', align='L')
        self.cell(0, 6, f'{report_date} (Data through {trading_date})', new_x='LMARGIN', new_y='NEXT', align='L')
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def chapter_title(self, title):
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(44, 82, 130)
        self.cell(0, 10, title, new_x='LMARGIN', new_y='NEXT', align='L')
        self.ln(2)

    def section_title(self, title):
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(74, 85, 104)
        self.cell(0, 8, title, new_x='LMARGIN', new_y='NEXT', align='L')
        self.ln(1)

    def body_text(self, text):
        self.set_font('Helvetica', '', 10)
        self.set_text_color(51, 51, 51)
        self.multi_cell(0, 6, text)
        self.ln(3)

    def callout(self, text, fill=(235, 248, 255), color=(51, 51, 51)):
        self.set_fill_color(*fill)
        self.set_font('Helvetica', '', 10)
        self.set_text_color(*color)
        self.multi_cell(0, 6, text, fill=True)
        self.ln(3)

    def table_header(self, cols):
        self.set_font('Helvetica', 'B', 9)
        self.set_fill_color(44, 82, 130)
        self.set_text_color(255, 255, 255)
        for width, label, align in cols:
            kw = {'align': align, 'fill': True}
            if align == 'L' and width != 0:
                kw = {'align': align, 'fill': True}
            self.cell(width, 7, label, align=align, fill=True)
        self.ln()

    def table_row(self, cells, fill, bold_cols=(), color=(51, 51, 51)):
        for i, (width, text, align) in enumerate(cells):
            self.set_font('Helvetica', 'B' if i in bold_cols else '', 9)
            self.set_text_color(*color)
            self.set_fill_color(247, 250, 252) if fill else self.set_fill_color(255, 255, 255)
            self.cell(width, 6, text, align=align, fill=fill)
        self.ln()

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by History Rhymes Agent | Not investment advice | Page {self.page_no()}', align='C')

pdf = PDF()
pdf.add_page()

# ============ EXECUTIVE SUMMARY ============
summary = (
    "Executive Summary: A new plot twist this week. On Friday, newly installed Fed Chair Kevin Warsh "
    "reaffirmed the inflation fight and signaled that RATE HIKES are back in play, with inflation stuck at 3.4% "
    "(July CPI) and crude oil up 45% year-to-date on war risk. Market-implied odds for a September FOMC hike "
    "flipped to roughly a coin flip (CNBC), the 10-year yield backed up to 4.72%, and the S&P 500 faded from "
    "within 0.6% of its 52-week high to close at 7,711.76 (-0.25%). The tape now sits at three-way historical "
    "convergence: the 1999-2000 Fed-hiking-into-a-bubble pattern, the 1972-74 Nifty Fifty concentration and "
    "1970s oil-shock inflation regime, and the late-August 1987 complacency setup. Meanwhile gold (+30% y/y, "
    "near records) and Bitcoin (-28% y/y) are staging a distinctly 1970s-style rotation toward hard money."
)
pdf.set_fill_color(235, 248, 255)
pdf.set_font('Helvetica', '', 10)
pdf.set_text_color(51, 51, 51)
pdf.multi_cell(0, 6, summary, fill=True)
pdf.ln(5)

# ============ THIS WEEK IN HEADLINES ============
pdf.chapter_title('This Week in Headlines')
headlines = [
    ('"Fed Chair Warsh signals rate hikes may be needed with inflation still elevated"', 'AP News, Aug 28'),
    ('"September Fed decision is now a coin flip as rate hike odds increase post-Warsh"', 'CNBC, Aug 28'),
    ('"Wall Street ends lower after Fed Chair Warsh reaffirms inflation fight"', 'Reuters, Aug 28'),
    ('"July CPI Report Shows Inflation at a 3.4% Annual Rate"', 'Morningstar, Aug 12'),
    ('"The S&P 500 keeps climbing on days when stocks broadly struggle"', 'MarketWatch, Aug 29'),
    ('"The S&P 500 Is Flashing a Warning Signal Not Seen in Decades"', 'Yahoo Finance, Aug 29'),
    ('"Norway wealth fund sounds alarm on AI stock market bubble"', 'DW, Aug 17'),
    ('"Ray Dalio: AI bubble nearing 1929, 2000 levels - wealth is not the same as money"', 'Fortune, Aug 4'),
]
pdf.table_header([(0, 'Headline', 'L'), (40, 'Source', 'L')])
fill = True
for title, src in headlines:
    pdf.table_row([(0, title, 'L'), (40, src, 'L')], fill)
    fill = not fill
pdf.ln(4)

# ============ CURRENT MARKET SNAPSHOT ============
pdf.chapter_title('Current Market Snapshot (Friday, Aug 28 Close)')
rows = [
    ('S&P 500', '7,711.76', '-0.25%', '+1.47%', '+19.4%'),
    ('Nasdaq', '26,402.42', '-0.52%', '-2.53%', '+23.1%'),
    ('Dow Jones', '53,560.00', '-0.02%', '+4.86%', '+17.6%'),
    ('Russell 2000', '2,972.37', '-1.39%', '+2.29%', '+25.6%'),
    ('10Y Treasury', '4.72%', '+5 bps', '+25 bps (3m)', '+52 bps (1y)'),
    ('13W T-Bill', '3.73%', '+5 bps', '+11 bps (3m)', '-32 bps (1y)'),
    ('VIX', '14.43', '-0.6%', '-10.1%', '0%'),
    ('USD Index', '99.68', '+0.5%', '+0.5%', '+2.0%'),
    ('Crude Oil', '83.40', '-0.2%', '-9.5%', '+30.3%'),
    ('Gold', '4,529.90', '-1.73%', '+1.2%', '+30.4%'),
    ('Bitcoin (Aug 29)', '77,634', '-3.27%', '+29.5%', '-28.4%'),
    ('NVIDIA', '217.55', '-4.57%', '-3.0%', '+24.9%'),
    ('Apple', '319.70', '+1.63%', '+4.4%', '+37.7%'),
    ('Microsoft', '513.53', '+1.68%', '+11.5%', '+1.4%'),
    ('Tesla', '348.75', '-1.71%', '-16.1%', '+4.5%'),
    ('Broadcom', '368.79', '-0.74%', '-19.8%', '+24.0%'),
    ('AMD', '465.58', '-2.33%', '-8.7%', '+186.3%'),
]
pdf.table_header([(44, 'Metric', 'L'), (34, 'Level', 'C'), (24, '1-Day', 'C'), (46, '3-Month', 'C'), (0, '1-Year', 'L')])
fill = True
for r in rows:
    c = (229, 62, 62) if (r[0].startswith('NV') or r[0].startswith('Br') or r[0].startswith('Bi')) and float(r[2].rstrip('%').replace(' bps', '99').replace('+', '1').replace('-', '9') if r[2].endswith('%') else 0) > 999 else (51, 51, 51)
    pdf.table_row([(44, r[0], 'L'), (34, r[1], 'C'), (24, r[2], 'C'), (46, r[3], 'C'), (0, r[4], 'L')], fill, bold_cols=(1,), color=(51, 51, 51))
    fill = not fill
pdf.ln(3)
pdf.set_font('Helvetica', 'I', 9)
pdf.set_text_color(100, 100, 100)
pdf.multi_cell(0, 5, 'YTD scorecard: S&P 500 +12.4%, Nasdaq +13.6%, Dow +10.7%, Russell 2000 +18.5%, Crude +45.5%, Gold +5.0%, Bitcoin -12.5%, NVIDIA +15.2%. Yields shown as raw percent (10Y = 4.72%).')
pdf.ln(4)

# ============ VALUATION & MACRO ============
pdf.section_title('Key Valuation & Macro Context')
pdf.table_header([(56, 'Indicator', 'L'), (36, 'Approx. Level', 'C'), (0, 'Historical Context', 'L')])
val_metrics = [
    ('Shiller CAPE', '~41-42', 'Top 1% of 155-year history; only Mar 2000 (~44) was higher'),
    ('S&P 500 Forward P/E', '~22-23x', 'Below 2000 (~27x) but far above the long-term mean (~16x)'),
    ('Top-10 Concentration', '~36-40%', 'Highest on record; exceeds dot-com peak (~27%)'),
    ('CPI Inflation', '3.4% (July)', 'Sticky above target for a 3rd year; Fed Chair Warsh calls it too high'),
    ('Fed Policy Stance', 'Hold, hikes "in play"', 'Sept FOMC a coin flip; cuts from 2025 partially reversed'),
    ('10Y vs 13W Spread', '+0.99 pp', 'Curve re-steepened from BOTH ends since 2025 - term-premium / fiscal signature'),
    ('Crude Oil', '83.40, +45.5% YTD', 'War-driven supply risk; 1973 and 2007-style energy shock profile'),
    ('VIX', '14.43', 'Complacent; pre-Aug-2007 vol levels; no tail risk priced'),
]
fill = True
for ind, lvl, ctx in val_metrics:
    pdf.table_row([(56, ind, 'L'), (36, lvl, 'C'), (0, ctx, 'L')], fill, bold_cols=(1,))
    fill = not fill
pdf.ln(4)

# ============ KEY HISTORICAL PARALLELS ============
pdf.add_page()
pdf.chapter_title('Key Historical Parallels')

# Parallel 1
pdf.section_title('1. 1999-2000: Fed Hiking Into a Bubble [HIGH SIMILARITY]')
pdf.body_text('This week transformed this parallel from background hum to headline. In June 1999 the Fed began tightening into a record-valuation, hyper-concentrated tech market. The market ignored the first hikes - the Nasdaq RALLIED another ~85% before peaking 9 months later (Mar 10, 2000) - and then lost 78% over 2.5 years once hikes met decelerating earnings.')
pdf.table_header([(48, 'Metric', 'L'), (36, 'March 2000', 'C'), (0, 'August 2026', 'L')])
p1 = [
    ('Forward P/E', '27x', '~22-23x'),
    ('CAPE (peak/now)', '44.2', '~41-42'),
    ('Top-10 concentration', '27%', '36-40% (worse)'),
    ('10-Year Treasury', '6.0%', '4.72% and rising'),
    ('Fed posture', '9 months into hikes', 'Hike threat just (re)started'),
    ('Leadership', 'Profitless .coms', 'Profitable AI giants (real FCF)'),
]
fill = True
for a, b, c in p1:
    pdf.table_row([(48, a, 'L'), (36, b, 'C'), (0, c, 'L')], fill, bold_cols=(1,))
    fill = not fill
pdf.ln(3)
pdf.callout('Key Rhyme: A Fed pivoting hawk at record valuations does NOT detonate the bubble on day one - in 1999-2000 the blow-off top came AFTER the first hikes. But when tightening meets decelerating capex returns, the unwind is violent. The $600B+/yr hyperscaler capex bill is 2026\'s version of 2000\'s telecom overbuild: the spending must earn its keep in measured revenue, not narratives.', fill=(235, 248, 255))

# Parallel 2
pdf.section_title('2. 1972-74 + the 1970s Regime: Concentration, Oil Shock, Hard Money [HIGH SIMILARITY]')
pdf.body_text('The second rhyme is not one bubble but a regime - and 2026 keeps acquiring 1970s features:')
pdf.body_text('- Nifty Fifty concentration: In Jan 1973, 50 "can\'t-lose" growth darlings peaked at extreme premiums. They held up while the broad market rolled over, then fell 60-90% in the 1973-74 bear as the S&P dropped 48%. Today: top-10 = ~36-40% of the S&P; Mag-7/AI leaders are the Nifty Fifty, and MarketWatch notes the index "keeps climbing on days when stocks broadly struggle" - eroding breadth.')
pdf.body_text('- Supply shock inflation: CPI 3.4% with crude +45.5% YTD on an active war echoes Oct 1973 (embargo: oil quadrupled, CPI went 3.6% -> 12%, S&P -48% into Sep 1974) and 2007-08 (oil through the roof, CPI sticky, equities at highs in May 2007).')
pdf.body_text('- New Fed chair, inflation fight: The Burns->Volcker handoff (1979) is the relevant precedent for a new chair forced to prioritize inflation over markets. Volcker\'s decisive hikes produced two recessions - credibility demanded it. Warsh\'s Friday remarks are the opening note of that score.')
pdf.body_text('- Hard-money rotation: Gold +30% y/y near all-time highs while Bitcoin is -28% y/y is a textbook 1970s rotation out of speculative assets into real stores of value - historically associated with fiscal dominance and persistent inflation.')
pdf.callout('The 1970s rhyme is slow-motion (a decade of sideways-in-real-terms equity returns, punctuated by repeated 25-50% drawdowns), not a single crash. It punishes concentration, leverage, and long-duration assets; it rewarded energy, commodities, and hard assets - and eventually, bought-cheap quality.', fill=(255, 250, 240))

# Parallel 3
pdf.add_page()
pdf.section_title('3. Late-August 1987: Complacency Meets a Hawkish Turn [MEDIUM-HIGH SIMILARITY]')
pdf.body_text('Forty-minus-one-weeks symmetry: the 1987 bull market peaked on August 25, 1987 with the market up strongly YTD, volatility at historic lows, a narrow rally, and a Fed (under new pressure) that had been tightening. Eight weeks later: Black Monday, -22.6% in one day, -34% top-to-bottom. The market made new highs again within 2 years.')
table3 = [
    ('Then (mid-1987)', 'Now (Aug 2026)'),
    ('YTD gains large, market at/near peak', 'S&P +12.4% YTD, 1.3% below 52-wk high'),
    ('Vol at multi-year lows', 'VIX 14.43, -10% over 3 months'),
    ('New/reassertive Fed stance', 'Warsh: hikes "in play" if CPI stays high'),
    ('Narrow leadership, rich multiples', 'Record concentration, CAPE ~41-42'),
    ('Trade/dollar friction', 'Tariff-era geopolitics, war risk premium'),
]
fill = True
for a, b in table3:
    pdf.table_row([(94, a, 'L'), (0, b, 'L')], fill, bold_cols=(0,) if fill else ())
    fill = not fill
pdf.ln(3)
pdf.callout('History\'s lesson: 1987 was followed by a fast recovery (new highs within ~2 years) even after the one-day crash - because the underlying economy stayed intact. 2026 has that same "good economy, bad market structure" fingerprint.', fill=(235, 248, 255))

# Parallel 4
pdf.section_title('4. 2007 Pre-GFC Complacency [MEDIUM-LOW - downgraded this week]')
pdf.body_text('Previously our lead parallel; the hike threat re-ranks it below the 2000 and 1970s patterns. The still-relevant echoes: VIX near 14 despite visible cracks, soft labor data under strong index levels, and consumer sentiment diverging from market highs. The 2007 lesson - complacency before the avalanche - applies if tightening cracks private credit or hyperscaler credit markets. Watch HY spreads and bank credit conditions, not just equities.')
pdf.ln(2)

# ============ FRIDAY TAPE ============
pdf.chapter_title('The Tell in Friday\'s Tape (Aug 28)')
pdf.body_text('Thursday: NVIDIA beat and jumped +8.7%; Nasdaq +1.6%; VIX -4.6%. Friday: everything reversed on the Warsh headlines -')
pdf.body_text('- NVDA -4.57% (giving back two-thirds of Thursday\'s pop), Broadcom -0.74% and -19.8% over 3 months, AMD -2.33%')
pdf.body_text('- Small caps hit hardest: Russell 2000 -1.39% - rate-hike odds are small-cap poison')
pdf.body_text('- Defensive mega-caps bid: Microsoft +1.68%, Apple +1.63%; Dow flat while Nasdaq -0.52%')
pdf.body_text('- 10Y +5bp to 4.72%; 13W bills +5bp; gold -1.73% (real-rate pressure); USD +0.52%')
pdf.callout('Interpretation: This was a textbook hawkish-repricing session - duration and leverage sold, defensives bought. Three-month rotation (Dow +4.9% vs Nasdaq -2.5%; Broadcom -19.8% while Microsoft +11.5%) shows the "old economy leads while the growth complex tops" pattern of early 2000 and 1972. One session proves nothing; the pattern across weeks is the signal.', fill=(245, 245, 245))

# ============ RHYME PATTERNS ============
pdf.add_page()
pdf.chapter_title('The Rhyme Patterns')
patterns = [
    ('Pattern 1: Valuation Extremes [CRITICAL]', 'CAPE ~41-42 has been exceeded once in 155 years (Mar 2000). Historically, starting CAPE above 35 has produced strongly sub-par real returns over the following decade. A hawkish Fed removes the multiple-expansion escape hatch: from these levels, returns must come from earnings, not re-rating.'),
    ('Pattern 2: Concentration + Breadth Decay [CRITICAL]', 'Top-10 weight (~36-40%) is the highest on record, and the index "climbs while the tape struggles" - a divergence pattern seen before 1929, 1972, 2000, and 2021. Each resolved in a drawdown of 30-78% within 12 months of the signal. This is the market\'s single most dangerous structural feature.'),
    ('Pattern 3: Tightening Into Strength [WATCH -> HIGH]', 'The one thing a valuation regime of this class cannot absorb is a sustained hawkish turn. Septembers after hawkish Jackson Hole windows (Aug 1987, Sep 1999, Sep 2000, Aug-Sept 2007) were all damaging. The September FOMC is now a coin flip; a hike (or hawkish hold plus a hot CPI print) is the historically loaded scenario.'),
    ('Pattern 4: Supply-Shock Economics [WATCH]', 'Crude +45.5% YTD with an active war = 1973/1990/2007-style energy shock. Oil shocks + sticky CPI + tightening Fed has been the single most reliable crash cocktail in the postwar record.'),
    ('Pattern 5: Hard-Money Rotation [WATCH]', 'Gold +30% y/y at records; Bitcoin -28% y/y. Central-bank gold demand and de-dollarization hedges echo the early-1970s. When investors pay 10-year yields of 4.7% AND buy gold simultaneously, the market is signaling it wants protection from both inflation and the issuer.'),
]
for title, txt in patterns:
    pdf.section_title(title)
    pdf.body_text(txt)

# ============ OUTCOMES ============
pdf.chapter_title('What Happened After Each Parallel')
pdf.table_header([(52, 'Parallel', 'L'), (62, 'Historical Outcome', 'C'), (0, 'Timeline', 'L')])
outcomes = [
    ('Mar 2000 peak (hikes began Jun 1999)', 'Nasdaq -78%, S&P -49%', '2.5 yrs to bottom'),
    ('Jan 1973 Nifty Fifty top', 'Leaders -60-90%, S&P -48%', '21 months to bottom'),
    ('Aug 25, 1987 peak', '-22.6% day, -34% top-to-bottom', '8 weeks; new highs ~2 yrs'),
    ('Oct 1973 oil embargo', 'CPI 3.6% -> 12%, S&P -48%', '11 months into bear'),
    ('May 2007 complacency', 'S&P -57% (GFC)', '17 months to bottom'),
]
fill = True
for a, b, c in outcomes:
    pdf.table_row([(52, a, 'L'), (62, b, 'C'), (0, c, 'L')], fill, bold_cols=(), color=(160, 60, 40))
    fill = not fill
pdf.ln(4)

# ============ BULL CASE ============
pdf.chapter_title('Why This Time Might Be Different (The Bull Case)')
pdf.body_text('- The AI leaders are genuinely profitable with real free cash flow - unlike profitless 1999s. NVIDIA trades near ~30x forward, not 100x+.')
pdf.body_text('- Breadth is improving under the surface: small caps (+18.5% YTD) are LEADING, the opposite of late 1999 when breadth collapsed. Equal-weight participation in 2026 is healthier than 2000 or 2021.')
pdf.body_text('- The Fed is not hostage: bills near 3.7% mean policy can still go in EITHER direction if growth cracks - unlike 2000 (8.5%) or 2007 (5.25%).')
pdf.body_text('- Valuation is extreme but not unanimous: a cash bill yields ~3.7%, so no one is forced up the risk curve; discipline exists on the margin.')
pdf.body_text('- Hyperscalers self-fund capex from profits (unlike 2000 telecoms on borrowed money), and AI demand signals (power, chips, cloud backlogs) remain measurable and real.')
pdf.ln(3)

# ============ RISKS ============
pdf.set_fill_color(255, 245, 245)
pdf.set_text_color(229, 62, 62)
pdf.set_font('Helvetica', 'B', 10)
pdf.cell(0, 6, 'Primary Risks:', new_x='LMARGIN', new_y='NEXT')
pdf.set_font('Helvetica', '', 10)
pdf.multi_cell(0, 6, '1. Hawkish accident: a hike (or two hawkish holds plus hot CPI) into record concentration. 2. Concentration cascade: a Mag-7 stumble has no shock absorbers at 36-40% index weight. 3. Capex cliff: AI spend must show proportional revenue by 2027 or multiples compress. 4. Supply shock escalation: oil toward $100 would force Warsh\'s hand. 5. Term-premium bleed: 10Y through cycle highs pressures everything from equity multiples to housing.', fill=True)
pdf.set_text_color(51, 51, 51)
pdf.ln(4)

# ============ CONCLUSION ============
pdf.chapter_title('Conclusion')
pdf.body_text('"History doesn\'t repeat itself, but it often rhymes." Three rhymes are sounding at once, and this week\'s Warsh pivot just raised their volume:')
pdf.body_text('1. 1999-2000 - a Fed tightening into record valuation and concentration. Markets ignore the first hikes, then punish the last ones.')
pdf.body_text('2. 1972-74 + 1970s regime - concentrated leadership, oil-shock inflation (crude +45% YTD), a new chair choosing credibility, hard-money rotation (gold records, Bitcoin down).')
pdf.body_text('3. Late-August 1987 - complacent vol, rich multiples, hawkish turn timed to the late-August policy window. Watch the next 8 weeks, not the next 8 days.')
pdf.callout('Bottom line: The market is priced for a perfect decade and priced for a friendly Fed - and can no longer have both. This setup does not demand an imminent crash call; it demands humility about forward returns and respect for the September FOMC. If inflation cooperates and 2027 earnings validate the capex, this rhymes with 1996 (expensive but extendable). If not, the precedents are written in the table above. Watch: (a) the September FOMC and odds of a hike, (b) CPI releases, (c) hyperscaler guidance on 2027 capex, (d) high-yield spreads, (e) whether the "index up, tape down" breadth signal persists.', fill=(235, 248, 255))
pdf.ln(4)
pdf.set_font('Helvetica', 'I', 9)
pdf.set_text_color(110, 110, 110)
pdf.multi_cell(0, 5, 'Methodology note: Market data from Yahoo Finance (chart API), Friday Aug 28, 2026 close (Bitcoin as of Aug 29). Headlines from AP, Reuters, CNBC, MarketWatch, Yahoo Finance, Morningstar, via RSS. Historical parallels are analogies, not predictions. This report is not investment advice.')

# Save PDF
output_path = os.path.join(output_dir, '2026-08-29_history_rhymes.pdf')
pdf.output(output_path)
print(f'PDF generated successfully: {output_path}')