#!/usr/bin/env python3
"""History Rhymes report for August 30, 2026 - data through Friday Aug 28 close + weekend headlines Aug 29-30."""

import os
from fpdf import FPDF

trading_date = "August 28, 2026"
report_date = "August 30, 2026"
output_dir = r'C:\Users\thadd\OneDrive\Desktop\Spocks Reports\history_rhymes'
os.makedirs(output_dir, exist_ok=True)

class PDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 16)
        self.set_text_color(26, 54, 93)
        self.cell(0, 10, 'History Rhymes - Market Pattern Analysis', new_x='LMARGIN', new_y='NEXT', align='L')
        self.set_font('Helvetica', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, 'Historical Parallels to Current Market Conditions', new_x='LMARGIN', new_y='NEXT', align='L')
        self.cell(0, 6, f'{report_date} (Data through {trading_date} close + weekend news)', new_x='LMARGIN', new_y='NEXT', align='L')
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def chapter_title(self, title):
        self.set_font('Helvetica', 'B', 14)
        self.set_text_color(44, 82, 130)
        self.cell(0, 10, title, new_x='LMARGIN', new_y='NEXT', align='L')
        self.ln(2)

    def section_title(self, title):
        self.set_font('Helvetica', 'B', 12)
        self.set_text_color(74, 85, 104)
        self.cell(0, 8, title, new_x='LMARGIN', new_y='NEXT', align='L')
        self.ln(1)

    def body_text(self, text):
        self.set_font('Helvetica', '', 10)
        self.set_text_color(51, 51, 51)
        self.multi_cell(0, 6, text)
        self.ln(3)

    def callout(self, text, fill=(235, 248, 255), color=(51, 51, 51)):
        self.set_fill_color(*fill)
        self.set_font('Helvetica', '', 10)
        self.set_text_color(*color)
        self.multi_cell(0, 6, text, fill=True)
        self.ln(3)

    def table_header(self, cols):
        self.set_font('Helvetica', 'B', 9)
        self.set_fill_color(44, 82, 130)
        self.set_text_color(255, 255, 255)
        for width, label, align in cols:
            self.cell(width, 7, label, align=align, fill=True)
        self.ln()

    def table_row(self, cells, fill, bold_cols=(), color=(51, 51, 51)):
        for i, (width, text, align) in enumerate(cells):
            self.set_font('Helvetica', 'B' if i in bold_cols else '', 9)
            self.set_text_color(*color)
            self.set_fill_color(247, 250, 252) if fill else self.set_fill_color(255, 255, 255)
            self.cell(width, 6, text, align=align, fill=fill)
        self.ln()

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by History Rhymes Agent | Not investment advice | Page {self.page_no()}', align='C')

pdf = PDF()
pdf.add_page()

# ============ EXECUTIVE SUMMARY ============
summary = (
    "Executive Summary: The weekend added three new threads to the tape. First, the market digest story: the WSJ reports "
    "'Markets Brace for Possible Rate Hike' after Fed Chair Kevin Warsh's Jackson Hole hawkish turn, meaning Monday's open "
    "will be the first session that fully prices a rate-hike scenario at record valuations. Second, a supply-side wildcard: "
    "President Trump announced a deal with Venezuela securing access to more than 65 billion barrels of oil reserves - a "
    "potential 1986-style supply valve that could deflate the energy-driven inflation squeeze, or simply redraw resource "
    "geopolitics. Third, the AI regime itself is consolidating: OpenAI will cut off model access to Cursor after SpaceX's "
    "acquisition of the startup, Meta agreed to an $18 billion settlement that puts TikTok and YouTube on notice, and "
    "MarketWatch warns that blistering corporate earnings growth 'is not likely to last.' The historical convergences are "
    "unchanged from Friday - 1999-2000 (hikes into a bubble), the 1970s regime (concentration, oil, hard money), and "
    "late-August 1987 (complacency window) - but the weekend sharpened the 2000 parallel and injected a fresh supply-side "
    "wildcard into the 1970s one."
)
pdf.set_fill_color(235, 248, 255)
pdf.set_font('Helvetica', '', 10)
pdf.set_text_color(51, 51, 51)
pdf.multi_cell(0, 6, summary, fill=True)
pdf.ln(5)

# ============ WEEKEND HEADLINES ============
pdf.chapter_title('This Weekend in Headlines (Aug 29-30)')
headlines = [
    ('"Markets Brace for Possible Rate Hike After Kevin Warsh\'s Hawkish Turn"', 'WSJ via Reuters, Aug 30'),
    ('"Trump announces deal with Venezuela to secure more than 65 billion barrels of oil reserves"', 'CNBC, Aug 30'),
    ('"OpenAI to end model access to Cursor after acquisition by Elon Musk\'s SpaceX"', 'CNBC, Aug 29'),
    ('"Meta\'s $18 billion settlement puts TikTok and YouTube on notice. Who\'s next on the firing line?"', 'CNBC, Aug 29'),
    ('"Tech backlash reaches fever pitch as AI angst collides with social media fears"', 'CNBC, Aug 29'),
    ('"Corporate earnings have been growing at a blistering pace. Here\'s why that\'s not likely to last."', 'MarketWatch, Aug 29'),
    ('"Where are all the new jobs? Hiring slows again - and it probably won\'t speed up soon."', 'MarketWatch, Aug 29'),
    ('"K, C or E? Why economists can\'t agree on the shape of today\'s economy"', 'CNBC, Aug 29'),
    ('"The Fed confronts a powerful new economic force"', 'Washington Post, Aug 29'),
    ('"Iran trade falls as Supreme Leader Khamenei urges less reliance on the U.S. dollar"', 'CNBC, Aug 29'),
]
pdf.table_header([(0, 'Headline', 'L'), (40, 'Source', 'L')])
fill = True
for title, src in headlines:
    pdf.table_row([(0, title, 'L'), (40, src, 'L')], fill)
    fill = not fill
pdf.ln(4)

# ============ CURRENT MARKET SNAPSHOT ============
pdf.chapter_title('Current Market Snapshot (Friday, Aug 28 Close)')
rows = [
    ('S&P 500', '7,711.76', '-0.25%', '+1.47%', '+19.4%'),
    ('Nasdaq', '26,402.42', '-0.52%', '-2.53%', '+23.1%'),
    ('Dow Jones', '53,560.00', '-0.02%', '+4.86%', '+17.6%'),
    ('Russell 2000', '2,972.37', '-1.39%', '+2.29%', '+25.6%'),
    ('10Y Treasury', '4.72%', '+5 bps', '+25 bps (3m)', '+52 bps (1y)'),
    ('13W T-Bill', '3.73%', '+5 bps', '+11 bps (3m)', '-32 bps (1y)'),
    ('VIX', '14.43', '-0.6%', '-10.1%', '0%'),
    ('USD Index', '99.70', '+0.5%', '+0.5%', '+1.3%'),
    ('Crude Oil', '83.40', '-0.2%', '-9.5%', '+27.2%'),
    ('Gold', '4,529.90', '-1.73%', '+1.2%', '+27.6%'),
    ('Bitcoin (weekend)', '78,173', '+0.4% since Fri', '+31.3%', '-28.2%'),
    ('NVIDIA', '217.55', '-4.57%', '-2.9%', '+25.1%'),
    ('Apple', '319.70', '+1.63%', '+4.5%', '+38.2%'),
    ('Microsoft', '513.53', '+1.68%', '+11.7%', '+2.2%'),
    ('Tesla', '348.75', '-1.71%', '-16.1%', '+4.5%'),
    ('Broadcom', '368.79', '-0.74%', '-19.7%', '+24.9%'),
    ('AMD', '465.58', '-2.33%', '-8.7%', '+186.3%'),
]
pdf.table_header([(44, 'Metric', 'L'), (34, 'Level', 'C'), (26, '1-Day', 'C'), (42, '3-Month', 'C'), (0, '1-Year', 'L')])
fill = True
for r in rows:
    pdf.table_row([(44, r[0], 'L'), (34, r[1], 'C'), (26, r[2], 'C'), (42, r[3], 'C'), (0, r[4], 'L')], fill, bold_cols=(1,))
    fill = not fill
pdf.ln(3)
pdf.set_font('Helvetica', 'I', 9)
pdf.set_text_color(100, 100, 100)
pdf.multi_cell(0, 5, 'YTD scorecard: S&P 500 +12.4%, Nasdaq +13.6%, Dow +10.7%, Russell 2000 +18.5%, Crude +45.5%, Gold +5.0%, Bitcoin -11.9%, NVIDIA +15.3%, AMD +108%. Yields shown as raw percent (10Y = 4.72%). Bitcoin trades through the weekend; equities closed Friday.')
pdf.ln(4)

# ============ VALUATION & MACRO ============
pdf.section_title('Key Valuation & Macro Context')
pdf.table_header([(56, 'Indicator', 'L'), (36, 'Approx. Level', 'C'), (0, 'Historical Context', 'L')])
val_metrics = [
    ('Shiller CAPE', '~41-42', 'Top 1% of 155-year history; only Mar 2000 (~44) was higher'),
    ('S&P 500 Forward P/E', '~22-23x', 'Below 2000 (~27x) but far above the long-term mean (~16x)'),
    ('Top-10 Concentration', '~36-40%', 'Highest on record; exceeds the dot-com peak (~27%)'),
    ('CPI Inflation', '3.4% (July)', 'Sticky above target for a third year; Warsh calls it too high'),
    ('Fed Policy Stance', 'Hikes "in play"', 'Sept FOMC seen as near coin flip; bond market already pricing one'),
    ('10Y vs 13W Spread', '+0.99 pp', 'Re-steepening from both ends - term-premium / fiscal signature'),
    ('Crude Oil', '83.40, +45.5% YTD', 'War-driven supply risk; now partially hedged by the Venezuela deal'),
    ('VIX', '14.43', 'Complacent; pre-Aug-2007 volatility levels; no tail risk priced'),
    ('Labor Market', 'Hiring slows again', '2007-style soft patches surfacing under index highs'),
]
fill = True
for ind, lvl, ctx in val_metrics:
    pdf.table_row([(56, ind, 'L'), (36, lvl, 'C'), (0, ctx, 'L')], fill, bold_cols=(1,))
    fill = not fill
pdf.ln(4)

# ============ KEY HISTORICAL PARALLELS ============
pdf.add_page()
pdf.chapter_title('Key Historical Parallels')

# Parallel 1
pdf.section_title('1. 1999-2000: Fed Hiking Into a Bubble [HIGH - SHARPENED THIS WEEKEND]')
pdf.body_text('In June 1999 the Fed began tightening into a record-valuation, hyper-concentrated tech market. The market ignored the first hikes - the Nasdaq rallied another ~85% before peaking on Mar 10, 2000 - and then lost 78% over 2.5 years once hikes met decelerating earnings. This weekend added TWO ingredients that were present in 2000 and missing from our earlier notes:')
pdf.body_text('- Earnings deceleration warning: MarketWatch reports that today\'s "blistering" corporate earnings pace "is not likely to last." In 2000 the trigger was exactly this: Q1-2000 earnings disappointments and warnings from market leaders collided with six months of accumulated Fed hikes. The bubble did not pop on the hikes; it popped when the earnings story cracked.')
pdf.body_text('- Consolidation and legal overhang: OpenAI cutting off Cursor after SpaceX\'s acquisition, and Meta\'s $18 billion settlement (with TikTok and YouTube "on notice"), echo the AOL-Time Warner mega-merger of January 2000 - the vertical-integration deal that coincided with the top - and the DOJ-vintage antitrust pressure on Microsoft that hung over the late-90s leadership into the bust.')
pdf.table_header([(48, 'Metric', 'L'), (36, 'March 2000', 'C'), (0, 'August 2026', 'L')])
p1 = [
    ('Forward P/E', '27x', '~22-23x'),
    ('CAPE (peak/now)', '44.2', '~41-42'),
    ('Top-10 concentration', '27%', '36-40% (worse)'),
    ('10-Year Treasury', '6.0%', '4.72% and rising'),
    ('Fed posture', '9 months into hikes', 'Hike threat just (re)started'),
    ('Earnings trend', 'Decelerating', 'Blistering - but "not likely to last"'),
    ('Platform structure', 'AOL-TW vertical mega-deal', 'SpaceX-Cursor consolidation, OpenAI walled gardens'),
    ('Legal overhang', 'DOJ vs Microsoft', 'Meta $18B settlement; more on notice'),
]
fill = True
for a, b, c in p1:
    pdf.table_row([(48, a, 'L'), (36, b, 'C'), (0, c, 'L')], fill, bold_cols=(1,))
    fill = not fill
pdf.ln(3)
pdf.callout('Key Rhyme: A Fed pivoting hawk at record valuations does NOT detonate the bubble on day one - in 1999-2000 the blow-off top came AFTER the first hikes. The detonator was earnings deceleration meeting tightening. That second ingredient is now visibly telegraphed. The $600B+/yr hyperscaler capex bill is 2026\'s version of 2000\'s telecom overbuild: the spending must earn its keep in measured revenue, not narratives.', fill=(235, 248, 255))

# Parallel 2
pdf.section_title('2. The 1970s Regime: Concentration, Oil Shock, Hard Money [HIGH - BUT A WILDCARD APPEARED]')
pdf.body_text('The second rhyme is not one bubble but a regime - and 2026 keeps acquiring 1970s features:')
pdf.body_text('- Nifty Fifty concentration: Top-10 weight at ~36-40% of the S&P exceeds even the dot-com peak; the index "climbs while the tape struggles" (MarketWatch) - eroding breadth, exactly the Jan-1973 signature.')
pdf.body_text('- Supply-shock inflation: CPI 3.4% with crude +45.5% YTD on an active war echoes Oct 1973 and 2007-08. BUT the Sunday Venezuela deal - more than 65 billion barrels of reserves under a US-secured arrangement - is a potential counter-echo of 1986, when Saudi production expansion collapsed oil, broke the inflation fever, and helped launch the Great Moderation. If barrels actually reach market, the supply-driven leg of the inflation squeeze loosens; if the deal stalls or war disrupts elsewhere, the 1970s profile tightens. This is now the swing variable in the inflation outlook.')
pdf.body_text('- New Fed chair, inflation fight: The Burns-to-Volcker handoff (1979) is the precedent for a new chair choosing credibility over markets. Warsh\'s Jackson Hole remarks are the opening note of that score.')
pdf.body_text('- Hard-money rotation: Gold near $4,530 (records) while Bitcoin is -28% year-over-year is a textbook 1970s rotation into real stores of value. Khamenei this weekend urging Iran to reduce reliance on the US dollar extends the de-dollarization motif visible in central-bank gold buying.')
pdf.callout('The 1970s rhyme is slow-motion - a decade of sideways-in-real-terms returns punctuated by repeated 25-50% drawdowns. It punishes concentration, leverage, and long-duration assets, and rewards energy, commodities, and hard assets. The Venezuela deal is the first genuine test of whether 2026 stays in that regime or starts to escape it.', fill=(255, 250, 240))

# Parallel 3
pdf.add_page()
pdf.section_title('3. Late-August 1987: Complacency Meets a Hawkish Turn [MEDIUM-HIGH]')
pdf.body_text('The anniversary symmetry remains: the 1987 bull market peaked Aug 25, 1987 - the same week 2026\'s market came within 0.6% of its 52-week high - with volatility at historic lows, a narrow rally, and a reassertive Fed. Eight weeks later: Black Monday, -22.6% in one day, -34% top-to-bottom. New highs again within 2 years because the economy stayed intact.')
table3 = [
    ('Then (mid-1987)', 'Now (Aug 2026)'),
    ('YTD gains large, market at/near peak', 'S&P +12.4% YTD, ~1.3% below 52-wk high'),
    ('Vol at multi-year lows', 'VIX 14.43, -10% over 3 months'),
    ('New/reassertive Fed stance', 'Warsh: hikes "in play"; market bracing'),
    ('Narrow leadership, rich multiples', 'Record concentration, CAPE ~41-42'),
    ('Trade/dollar friction', 'Tariff-era geopolitics, war risk premium'),
]
fill = True
for a, b in table3:
    pdf.table_row([(94, a, 'L'), (0, b, 'L')], fill, bold_cols=(0,) if fill else ())
    fill = not fill
pdf.ln(3)
pdf.callout('History\'s lesson: 1987 was followed by a fast recovery - new highs within ~2 years - because the underlying economy stayed intact. 2026 has that same "good economy, bad market structure" fingerprint. Watch the next 8 weeks, not the next 8 days.', fill=(235, 248, 255))

# Parallel 4
pdf.section_title('4. 2007 Pre-GFC Cracks [MEDIUM-LOW - LABOR ECHO STRENGTHENED]')
pdf.body_text('The 2007 echo remains a secondary theme, but the weekend labor data deepens it: "Where are all the new jobs? Hiring slows again - and it probably won\'t speed up soon" is precisely the kind of soft patch that appeared in the August-September 2007 window while the index sat near highs and VIX near record lows. CNBC\'s "K, C or E?" shape-of-the-economy debate captures a market that has stopped agreeing on fundamentals - also a late-cycle tell from 2006-07. The 2007 lesson: complacency before the avalanche. Watch high-yield spreads and credit conditions, not just equities.')
pdf.ln(2)

# ============ WEEKEND WEAVE ============
pdf.chapter_title('The Weekend Weave: How the New Threads Fit')
weave = [
    ('Warsh hike scenario', 'WSJ: markets brace; bond market already pricing a hike. Monday is the first full repricing session. The Septembears of 1987, 1999, 2000 and 2007 all began with exactly this kind of late-summer hawkish turn.'),
    ('Venezuela oil deal', '65B+ barrels secured. Bearish for crude (supply valve = potential 1986 rhyme, disinflationary relief) OR bullish geopolitically-neutral-only (implementation risk, OPEC responses). Crude closed +45.5% YTD; watch the Monday repricing of the war premium.'),
    ('OpenAI/SpaceX/Cursor', 'AI platform consolidation - 1999 AOL-Time Warner rhyme. Late-cycle vertical integration and walled gardens signal the land-grab phase is ending and the monetization/margin phase is beginning. Historically coincides with multiples peaking.'),
    ('Meta $18B settlement', 'Big Tech legal overhang mirrors DOJ-vintage Microsoft (1998-2001): regulatory cost rising exactly when the growth story must carry the index. "Who is next?" is the market\'s recurring question.'),
    ('Earnings warning', 'MarketWatch: blistering earnings pace "not likely to last" - the 2000 detonator. If 2027 earnings decelerate while hikes accumulate, the cycle-rhyme completes.'),
    ('Hiring slows', '2007-style labor softening under a complacent VIX. Fed faces stagflation-lite: too-hot CPI, cooling jobs - the worst corner of the policy box (Volcker territory).'),
]
pdf.table_header([(50, 'Thread', 'L'), (0, 'Historical Reading', 'L')])
fill = True
for a, b in weave:
    pdf.table_row([(50, a, 'L'), (0, b, 'L')], fill, bold_cols=(0,) if fill else ())
    fill = not fill
pdf.ln(3)

# ============ RHYME PATTERNS ============
pdf.add_page()
pdf.chapter_title('The Rhyme Patterns')
patterns = [
    ('Pattern 1: Valuation Extremes [CRITICAL]', 'CAPE ~41-42 has been exceeded once in 155 years (Mar 2000). Starting CAPE above 35 has historically produced strongly sub-par real returns over the following decade. A hawkish Fed removes the multiple-expansion escape hatch: from here, returns must come from earnings - and the weekend\'s headline warns those earnings may not last.'),
    ('Pattern 2: Concentration + Breadth Decay [CRITICAL]', 'Top-10 weight (~36-40%) is the highest on record, and the index climbs while the tape struggles - a divergence seen before 1929, 1972, 2000, and 2021. Each resolved in a 30-78% drawdown within roughly 12 months of the signal. Still the single most dangerous structural feature.'),
    ('Pattern 3: Tightening Into Strength [HIGH]', 'A valuation regime of this class cannot absorb a sustained hawkish turn. Hawkish-Jackson-Hole Septembers (1987, 1999, 2000, 2007) were all damaging. The September FOMC is now effectively a coin flip already priced into bonds; a hike or hawkish hold plus a hot CPI print is the historically loaded scenario.'),
    ('Pattern 4: Supply-Shock Economics [WATCH - NOW TWO-SIDED]', 'Crude +45.5% YTD with an active war is the 1973/2007 profile - but the Venezuela deal (65B+ barrels) is the first supply-side relief valve to appear. If it delivers barrels, this pattern downgrades; if it stalls, the pattern strengthens. Monday\'s oil tape is the first vote.'),
    ('Pattern 5: Hard-Money Rotation [WATCH]', 'Gold at records (+28% y/y); Bitcoin -28% y/y; Khamenei urging dollar-escape. When investors pay 4.7% for 10-year Treasuries AND buy gold simultaneously, the market is signaling it wants protection from both inflation and the issuer - an early-1970s signature.'),
    ('Pattern 6: Late-Cycle Platform Consolidation [NEW - WATCH]', 'OpenAI sealing access, SpaceX buying Cursor, Meta paying $18B: late-cycle vertical integration and legal costs. 1999-2000 rhyme (AOL-Time Warner, Microsoft antitrust). When platform wars shift from growth-at-all-costs to moats-and-lawyers, the land-grab stage is ending.'),
]
for title, txt in patterns:
    pdf.section_title(title)
    pdf.body_text(txt)

# ============ OUTCOMES ============
pdf.chapter_title('What Happened After Each Parallel')
pdf.table_header([(52, 'Parallel', 'L'), (62, 'Historical Outcome', 'C'), (0, 'Timeline', 'L')])
outcomes = [
    ('Mar 2000 peak (hikes began Jun 1999)', 'Nasdaq -78%, S&P -49%', '2.5 yrs to bottom'),
    ('Jan 1973 Nifty Fifty top', 'Leaders -60-90%, S&P -48%', '21 months to bottom'),
    ('Aug 25, 1987 peak', '-22.6% day, -34% top-to-bottom', '8 weeks; new highs ~2 yrs'),
    ('Oct 1973 oil embargo', 'CPI 3.6% -> 12%, S&P -48%', '11 months into bear'),
    ('Feb 1986 Saudi supply surge', 'Oil -69%, disinflation, boom resumed', 'The counter-example'),
    ('May 2007 complacency', 'S&P -57% (GFC)', '17 months to bottom'),
]
fill = True
for a, b, c in outcomes:
    pdf.table_row([(52, a, 'L'), (62, b, 'C'), (0, c, 'L')], fill, color=(160, 60, 40))
    fill = not fill
pdf.ln(4)

# ============ BULL CASE ============
pdf.chapter_title('Why This Time Might Be Different (The Bull Case)')
pdf.body_text('- The Venezuela deal could genuinely deflate the oil/energy leg of inflation - the 1986 rhyme - giving Warsh room to stay patient. Watch crude on Monday.')
pdf.body_text('- The AI leaders are genuinely profitable with real free cash flow - unlike profitless 1999s. NVIDIA trades near ~30x forward, not 100x+.')
pdf.body_text('- Breadth is improving under the surface: small caps (+18.5% YTD) are LEADING, the opposite of late 1999 when breadth collapsed.')
pdf.body_text('- The Fed is not hostage: bills near 3.7% mean policy can still go in EITHER direction if growth cracks - unlike 2000 (8.5%) or 2007 (5.25%).')
pdf.body_text('- Hyperscalers self-fund capex from profits, and AI demand signals (power, chips, cloud backlogs) remain measurable and real. Platform consolidation can also rationalize spending - the moat phase can extend winners.')
pdf.ln(3)

# ============ RISKS ============
pdf.set_fill_color(255, 245, 245)
pdf.set_text_color(229, 62, 62)
pdf.set_font('Helvetica', 'B', 10)
pdf.cell(0, 6, 'Primary Risks:', new_x='LMARGIN', new_y='NEXT')
pdf.set_font('Helvetica', '', 10)
pdf.multi_cell(0, 6, '1. Hawkish accident: a hike into record concentration; Monday is the first repricing session. 2. Concentration cascade: a Mag-7 stumble has no shock absorbers at 36-40% index weight. 3. Capex cliff + earnings deceleration arriving together - the 2000 detonator. 4. Venezuela deal fails to deliver barrels (or provokes responses) while war risk persists - oil toward $100 forces the Fed\'s hand. 5. Stagflation-lite: hiring slows while CPI stays 3.4%+ - the Volcker corner of the policy box. 6. Platform consolidation raises costs and squeezes dependents (Cursor-style players) - margin shock in the AI stack.', fill=True)
pdf.set_text_color(51, 51, 51)
pdf.ln(4)

# ============ CONCLUSION ============
pdf.chapter_title('Conclusion')
pdf.body_text('"History doesn\'t repeat itself, but it often rhymes." Three rhymes are still sounding at once - and the weekend rewrote one stanza and added two new ones:')
pdf.body_text('1. 1999-2000 - the Fed tightening into record valuation and concentration - now has its detonator storyline: an earnings-deceleration warning plus late-cycle platform consolidation (OpenAI/SpaceX/Cursor, Meta\'s $18B settlement). Markets ignore the first hikes, then punish the last ones when the earnings story cracks.')
pdf.body_text('2. The 1970s regime - concentrated leadership, oil-shock inflation, a new chair choosing credibility, hard-money rotation - just met its first real challenger: a 65-billion-barrel Venezuela deal that could rhyme with 1986 instead of 1973. Monday\'s crude tape is the vote.')
pdf.body_text('3. Late-August 1987 - complacent volatility, rich multiples, a hawkish turn timed to the late-August policy window. We are 3 trading days past the Aug 25 anniversary, inside the historical 8-week danger window. WSJ: "Markets brace for a possible rate hike."')
pdf.callout('Bottom line: The market is priced for a perfect decade and priced for a friendly Fed - and can no longer have both. Nothing this weekend demands an imminent-crash call; it demands humility about forward returns and respect for the September FOMC. If Venezuela barrels flow and 2027 earnings validate the capex, this rhymes with 1996 or 1986 - expensive but extendable. If not, the precedents are in the table above. Watch: (a) Monday\'s open and crude response to the Venezuela deal, (b) the September FOMC, (c) CPI releases, (d) hyperscaler guidance on 2027 capex, (e) high-yield spreads, (f) whether the "index up, tape down" breadth signal persists.', fill=(235, 248, 255))
pdf.ln(4)
pdf.set_font('Helvetica', 'I', 9)
pdf.set_text_color(110, 110, 110)
pdf.multi_cell(0, 5, 'Methodology note: Market data via Yahoo Finance API - equity/ETF/commodity readings through Friday Aug 28, 2026 close; Bitcoin quoted Sunday Aug 30 morning (trades through the weekend). Headlines via WSJ (Reuters-index), CNBC, MarketWatch, and Washington Post RSS through Sunday morning. Historical parallels are analogies, not predictions. This report is not investment advice.')

# Save PDF
output_path = os.path.join(output_dir, '2026-08-30_history_rhymes.pdf')
pdf.output(output_path)
print(f'PDF generated successfully: {output_path}')