#!/usr/bin/env python3
"""Generate History Rhymes market report for May 11, 2026 using fpdf2"""

from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        # Title
        self.set_font('Arial', 'B', 16)
        self.set_text_color(26, 54, 93)
        self.cell(0, 10, 'History Rhymes Market Report', 0, 1, 'L')
        self.set_font('Arial', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 6, 'Daily Analysis of Historical Market Parallels | May 11, 2026', 0, 1, 'L')
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Spock (History Rhymes Agent)', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Arial', 'B', 13)
        self.set_text_color(44, 82, 130)
        self.cell(0, 10, title, 0, 1, 'L')
        self.ln(2)
        
    def section_title(self, title, strength=""):
        self.set_font('Arial', 'B', 11)
        self.set_text_color(45, 55, 72)
        self.cell(0, 8, title, 0, 1, 'L')
        self.ln(1)
        
    def body_text(self, text):
        self.set_font('Arial', '', 10)
        self.set_text_color(51, 51, 51)
        self.multi_cell(0, 5, text)
        self.ln(3)
        
    def bullet_list(self, items):
        self.set_font('Arial', '', 10)
        self.set_text_color(51, 51, 51)
        for item in items:
            self.cell(5, 5, chr(149), 0, 0)  # bullet
            self.multi_cell(0, 5, f' {item}')
        self.ln(2)
        
    def alert_box(self, title, items, color='red'):
        colors = {
            'red': (229, 62, 62),
            'orange': (221, 107, 32),
            'blue': (66, 153, 225)
        }
        c = colors.get(color, (51, 51, 51))
        
        self.set_fill_color(254, 250, 250)
        self.set_draw_color(c[0], c[1], c[2])
        self.set_line_width(0.5)
        
        start_y = self.get_y()
        self.cell(190, 5, '', 'LRT', 1, 'L', True)
        
        self.set_font('Arial', 'B', 10)
        self.set_text_color(c[0], c[1], c[2])
        self.cell(5, 5, '', 'L', 0, 'L', True)
        self.cell(185, 5, title, 'R', 1, 'L', True)
        
        self.set_font('Arial', '', 10)
        self.set_text_color(51, 51, 51)
        for item in items:
            self.cell(5, 5, '', 'L', 0, 'L', True)
            self.cell(5, 5, chr(149), 0, 0, 'L', True)
            self.multi_cell(180, 5, f' {item}', 'R', 'L', True)
        
        self.cell(190, 2, '', 'LRB', 1, 'L', True)
        self.ln(5)
        
    def metric_box(self, label, value, subtext):
        self.set_fill_color(247, 250, 252)
        self.set_draw_color(226, 232, 240)
        self.rect(10, self.get_y(), 45, 25, 'DF')
        
        self.set_xy(10, self.get_y() + 2)
        self.set_font('Arial', 'B', 16)
        self.set_text_color(43, 108, 176)
        self.cell(45, 8, value, 0, 2, 'C')
        
        self.set_font('Arial', '', 8)
        self.set_text_color(113, 128, 150)
        self.cell(45, 4, label, 0, 2, 'C')
        
        self.set_font('Arial', '', 8)
        self.set_text_color(56, 161, 105)
        self.cell(45, 4, subtext, 0, 2, 'C')
        
        self.set_xy(60, self.get_y() - 18)

# Create PDF
pdf = PDF()
pdf.set_auto_page_break(auto=True, margin=15)
pdf.add_page()

# Executive Summary
pdf.set_fill_color(235, 248, 255)
pdf.set_draw_color(66, 153, 225)
pdf.rect(10, pdf.get_y(), 190, 30, 'DF')
pdf.set_xy(12, pdf.get_y() + 2)
pdf.set_font('Arial', 'B', 10)
pdf.set_text_color(43, 108, 176)
pdf.cell(0, 6, 'Executive Summary:', 0, 1)
pdf.set_font('Arial', '', 10)
pdf.set_text_color(51, 51, 51)
pdf.multi_cell(186, 5, 'The S&P 500 and Nasdaq have reached fresh record highs, with the CAPE ratio at ~39.8 - levels matching the dot-com bubble peak. Markets enter a critical week with inflation data and Iran tensions in focus. Six consecutive weeks of gains mirror 1999 patterns, though current companies show actual profitability unlike the dot-com era.')
pdf.ln(35)

# Current Market Snapshot
pdf.chapter_title('Current Market Snapshot')

# Metrics in a row
pdf.set_xy(10, pdf.get_y())
metrics = [
    ('S&P 500', '7,399', 'Record High'),
    ('Nasdaq', '26,247', 'Record High'),
    ('CAPE Ratio', '~39.8', 'Dot-com Levels'),
    ('Gains Streak', '6 Weeks', 'Momentum')
]

x_pos = 10
for label, value, subtext in metrics:
    pdf.set_fill_color(247, 250, 252)
    pdf.set_draw_color(226, 232, 240)
    pdf.rect(x_pos, pdf.get_y(), 45, 25, 'DF')
    
    pdf.set_xy(x_pos + 2, pdf.get_y() + 2)
    pdf.set_font('Arial', 'B', 14)
    pdf.set_text_color(43, 108, 176)
    pdf.cell(41, 8, value, 0, 2, 'C')
    
    pdf.set_font('Arial', '', 8)
    pdf.set_text_color(113, 128, 150)
    pdf.cell(41, 4, label, 0, 2, 'C')
    
    pdf.set_font('Arial', '', 8)
    pdf.set_text_color(56, 161, 105)
    pdf.cell(41, 4, subtext, 0, 2, 'C')
    
    x_pos += 47.5

pdf.ln(32)

# Historical Parallels
pdf.chapter_title('Historical Parallels Analysis')

# Dot-Com Bubble
pdf.section_title('1. The Dot-Com Bubble (1999-2000) [Strong Rhyme]')
pdf.alert_box('Key Parallels:', [
    'CAPE ratio at ~39.8 matches 1999-2000 peak levels (~44 at bubble top)',
    'Technology stocks driving record highs (AI narrative vs. internet narrative)',
    'Six consecutive weeks of gains echo late-1999 euphoria',
    'Market concentration above 2000 levels (Magnificent Seven = Nifty Fifty of today)'
], 'red')
pdf.set_font('Arial', 'I', 10)
pdf.set_text_color(51, 51, 51)
pdf.multi_cell(0, 5, 'Critical Difference: Today\'s AI companies are actually profitable with disciplined balance sheets, unlike 1999\'s revenue-less startups.')
pdf.ln(5)

# Nifty Fifty
pdf.section_title('2. The Nifty Fifty (1972) [Moderate Rhyme]')
pdf.alert_box('Key Parallels:', [
    '\'One decision stocks\' (Nifty Fifty) vs. today\'s \'Magnificent Seven\'',
    'Growth stocks bid to unreasonable heights due to perceived safety',
    'High valuations justified by "this time is different" narrative',
    'Severe bear market followed (1973-1974: S&P 500 down 48%)'
], 'orange')
pdf.set_font('Arial', 'I', 10)
pdf.set_text_color(51, 51, 51)
pdf.multi_cell(0, 5, 'Lesson: Even quality companies can become bad investments at extreme valuations.')
pdf.ln(5)

# Roaring Twenties
pdf.section_title('3. The Roaring Twenties (1929) [Weak Rhyme]')
pdf.alert_box('Key Parallels:', [
    'New transformative technology (radio/automobiles then, AI now)',
    'Massive infrastructure build-out creating speculation',
    'Margin debt expansion (then) vs. corporate debt for AI build-out (now)'
], 'blue')
pdf.set_font('Arial', 'I', 10)
pdf.set_text_color(51, 51, 51)
pdf.multi_cell(0, 5, 'Difference: Today\'s regulatory frameworks and Fed intervention tools differ significantly from 1929.')
pdf.ln(5)

# Pattern Identification Table
pdf.add_page()
pdf.chapter_title('Pattern Identification')

pdf.set_font('Arial', 'B', 10)
pdf.set_fill_color(44, 82, 130)
pdf.set_text_color(255, 255, 255)
pdf.cell(50, 8, 'Pattern', 1, 0, 'L', True)
pdf.cell(45, 8, 'Current (2026)', 1, 0, 'L', True)
pdf.cell(55, 8, 'Historical Parallel', 1, 0, 'L', True)
pdf.cell(40, 8, 'Strength', 1, 1, 'L', True)

pdf.set_font('Arial', '', 9)
pdf.set_text_color(51, 51, 51)

patterns = [
    ('Valuation', 'CAPE ~39.8', '1999 (~44), 1929 (~30)', 'Strong'),
    ('Leadership', 'Magnificent Seven', 'Nifty Fifty (1972), Tech (1999)', 'Strong'),
    ('Earnings Quality', 'Actually profitable', 'Mixed (better than 1999)', 'Weak'),
    ('Macro Environment', 'Fed on hold, sticky inflation', '1970s stagflation', 'Moderate'),
    ('Sector Rotation', 'Tech + Comm Services', '1999 (TMT focus)', 'Strong'),
]

fill = False
for pattern, current, parallel, strength in patterns:
    if fill:
        pdf.set_fill_color(247, 250, 252)
    else:
        pdf.set_fill_color(255, 255, 255)
    
    pdf.cell(50, 7, pattern, 1, 0, 'L', fill)
    pdf.cell(45, 7, current, 1, 0, 'L', fill)
    pdf.cell(55, 7, parallel, 1, 0, 'L', fill)
    pdf.cell(40, 7, strength, 1, 1, 'L', fill)
    fill = not fill

pdf.ln(8)

# Warning Signals
pdf.chapter_title('Warning Signals')

pdf.alert_box('High Risk Indicators:', [
    'CAPE ratio at levels seen only twice in history (1929, 2000)',
    'Geopolitical tensions (Iran) adding oil price pressure',
    'Fed divided on rate policy direction',
    'Six consecutive weeks of gains (momentum exhaustion risk)',
    'AI capex bubble concerns: $120B bond issuance predicted for 2025'
], 'red')

pdf.alert_box('Mitigating Factors:', [
    'Corporate earnings are real and growing (unlike 1999)',
    'Hyperscalers maintain disciplined balance sheets',
    'Strong employment data supports consumer spending',
    'Market breadth showing some improvement vs. pure megacap rally'
], 'blue')

# Historical Precedent Outcomes
pdf.chapter_title('Historical Precedent Outcomes')

pdf.set_font('Arial', 'B', 10)
pdf.set_fill_color(44, 82, 130)
pdf.set_text_color(255, 255, 255)
pdf.cell(70, 8, 'Historical Period', 1, 0, 'L', True)
pdf.cell(40, 8, 'Peak CAPE', 1, 0, 'L', True)
pdf.cell(80, 8, 'Subsequent 10-Year Returns', 1, 1, 'L', True)

pdf.set_font('Arial', '', 9)
pdf.set_text_color(51, 51, 51)

outcomes = [
    ('1929 (Great Depression)', '~30', '-1.4% annually'),
    ('1972 (Nifty Fifty)', '~18', '~2% annually'),
    ('2000 (Dot-Com)', '~44', '-3.0% annually'),
]

fill = False
for period, capepe, returns in outcomes:
    if fill:
        pdf.set_fill_color(247, 250, 252)
    else:
        pdf.set_fill_color(255, 255, 255)
    
    pdf.cell(70, 7, period, 1, 0, 'L', fill)
    pdf.cell(40, 7, capepe, 1, 0, 'L', fill)
    pdf.cell(80, 7, returns, 1, 1, 'L', fill)
    fill = not fill

# Current row (highlighted)
pdf.set_fill_color(254, 215, 215)
pdf.set_font('Arial', 'B', 9)
pdf.cell(70, 7, '2026 (Current)', 1, 0, 'L', True)
pdf.cell(40, 7, '~39.8', 1, 0, 'L', True)
pdf.cell(80, 7, 'Unknown', 1, 1, 'L', True)

pdf.ln(8)

# Key Takeaways
pdf.chapter_title('Key Takeaways')

pdf.set_font('Arial', 'B', 10)
pdf.set_text_color(44, 82, 130)
for i, (title, content) in enumerate([
    ('1. Valuation Risk:', 'Current CAPE levels (~39.8) place us in the top 1% of historical valuations, implying subpar returns over the next decade.'),
    ('2. Quality Matters:', 'Unlike 1999, today\'s leaders have real earnings - but that doesn\'t eliminate valuation risk.'),
    ('3. Macro Headwinds:', 'Sticky inflation and geopolitical tensions echo 1970s challenges, not 1990s Goldilocks conditions.'),
    ('4. Duration Risk:', 'High-duration growth stocks (Magnificent Seven) are most vulnerable if rates stay elevated.'),
    ('5. History\'s Lesson:', '"History doesn\'t repeat, but it often rhymes." The melody today resembles 1999 more than 1929, but the lyrics differ.')
], 1):
    pdf.cell(0, 6, f'{title} {content}', 0, 1)

pdf.ln(5)

# Bottom Line
pdf.set_fill_color(235, 248, 255)
pdf.set_draw_color(66, 153, 225)
pdf.rect(10, pdf.get_y(), 190, 20, 'DF')
pdf.set_xy(12, pdf.get_y() + 2)
pdf.set_font('Arial', 'B', 10)
pdf.set_text_color(43, 108, 176)
pdf.cell(0, 6, 'Bottom Line:', 0, 1)
pdf.set_font('Arial', '', 10)
pdf.set_text_color(51, 51, 51)
pdf.multi_cell(186, 5, 'The market is expensive by historical standards. While this doesn\'t predict an imminent crash, it does suggest below-average returns ahead. The key question: Is AI the "new economy" of 2026, or the "radio stocks" of 1929? Time will tell.')

# Save PDF
output_path = "C:/Users/thadd/OneDrive/Desktop/Spocks Reports/history_rhymes/2026-05-11_history_rhymes.pdf"
pdf.output(output_path)
print(f"PDF generated successfully: {output_path}")
