from fpdf import FPDF
from datetime import datetime

class PDF(FPDF):
    def header(self):
        self.set_font('helvetica', 'B', 12)
        self.cell(0, 10, 'Daily Brief - May 9, 2026', new_x="LMARGIN", new_y="NEXT", align='C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', align='C')

# Create PDF
pdf = PDF()
pdf.add_page()
pdf.set_auto_page_break(auto=True, margin=15)

# Title
pdf.set_font('helvetica', 'B', 20)
pdf.cell(0, 15, 'Daily Brief', new_x="LMARGIN", new_y="NEXT", align='C')
pdf.set_font('helvetica', '', 12)
pdf.cell(0, 10, 'Saturday, May 9, 2026 | 8:38 AM CDT', new_x="LMARGIN", new_y="NEXT", align='C')
pdf.ln(10)

# Market Overview
pdf.set_font('helvetica', 'B', 14)
pdf.cell(0, 10, 'Market Overview', new_x="LMARGIN", new_y="NEXT", align='L')
pdf.ln(2)

# Futures & Weekly Performance
pdf.set_font('helvetica', 'B', 12)
pdf.cell(0, 8, 'Market Futures & Weekly Performance', new_x="LMARGIN", new_y="NEXT", align='L')
pdf.set_font('helvetica', '', 11)
pdf.multi_cell(w=190, h=6, text='- S&P 500 & Nasdaq: Posted 6th consecutive weekly win', align='L')
pdf.multi_cell(w=190, h=6, text='- All-time highs: US stocks climbed to record highs on Friday with tech leading', align='L')
pdf.multi_cell(w=190, h=6, text='- Friday momentum: Strong finish driven by chip stocks rally and positive jobs data', align='L')
pdf.ln(5)

# Key Economic Data
pdf.set_font('helvetica', 'B', 12)
pdf.cell(0, 8, 'Key Economic Data - April Jobs Report (Released May 8)', new_x="LMARGIN", new_y="NEXT", align='L')
pdf.set_font('helvetica', '', 11)
pdf.multi_cell(w=190, h=6, text='- Nonfarm payrolls: +115,000 (vs. 55,000 forecast)', align='L')
pdf.multi_cell(w=190, h=6, text='- Previous month: 185,000 (strong March)', align='L')
pdf.multi_cell(w=190, h=6, text='- Unemployment rate: Held steady at 4.3%', align='L')
pdf.multi_cell(w=190, h=6, text='- Market reaction: Better-than-expected, signaling labor market resilience', align='L')
pdf.ln(5)

# Sector Highlights
pdf.set_font('helvetica', 'B', 12)
pdf.cell(0, 8, 'Sector Highlights', new_x="LMARGIN", new_y="NEXT", align='L')
pdf.set_font('helvetica', '', 11)
pdf.multi_cell(w=190, h=6, text='- Technology: Leading gains - record highs', align='L')
pdf.multi_cell(w=190, h=6, text='- Semiconductors: Chip stocks rallying', align='L')
pdf.multi_cell(w=190, h=6, text='- Broad Market: S&P 500 and Nasdaq at fresh highs', align='L')
pdf.ln(5)

# Geopolitical Notes
pdf.set_font('helvetica', 'B', 12)
pdf.cell(0, 8, 'Geopolitical Notes', new_x="LMARGIN", new_y="NEXT", align='L')
pdf.set_font('helvetica', '', 11)
pdf.multi_cell(w=190, h=6, text='- Iran Ceasefire: Remains intact - supporting market stability', align='L')
pdf.multi_cell(w=190, h=6, text='- Trump-Xi Summit: Upcoming deadline for U.S.-Iran war resolution discussions', align='L')
pdf.ln(5)

# Earnings Season
pdf.set_font('helvetica', 'B', 12)
pdf.cell(0, 8, 'Earnings Season', new_x="LMARGIN", new_y="NEXT", align='L')
pdf.set_font('helvetica', '', 11)
pdf.multi_cell(w=190, h=6, text='- S&P 500 companies continue reporting impressive results', align='L')
pdf.multi_cell(w=190, h=6, text='- Both percentage of companies beating estimates and magnitude of beats above historical averages', align='L')
pdf.multi_cell(w=190, h=6, text='- Next Week: Applied Materials among stocks reporting with earnings momentum', align='L')
pdf.ln(5)

# Market Sentiment
pdf.set_font('helvetica', 'B', 12)
pdf.cell(0, 8, 'Market Sentiment', new_x="LMARGIN", new_y="NEXT", align='L')
pdf.set_font('helvetica', '', 11)
pdf.multi_cell(w=190, h=6, text='Bullish Factors:', align='L')
pdf.multi_cell(w=190, h=6, text='  - Strong weekly streak (6 weeks of gains)', align='L')
pdf.multi_cell(w=190, h=6, text='  - Jobs data exceeding expectations', align='L')
pdf.multi_cell(w=190, h=6, text='  - Tech/semiconductor strength', align='L')
pdf.multi_cell(w=190, h=6, text='  - Record highs across major indices', align='L')
pdf.ln(3)
pdf.multi_cell(w=190, h=6, text='Watch Points:', align='L')
pdf.multi_cell(w=190, h=6, text='  - Trade negotiations (Trump-Xi summit)', align='L')
pdf.multi_cell(w=190, h=6, text='  - Iran situation developments', align='L')
pdf.multi_cell(w=190, h=6, text='  - Interest rate policy implications from jobs data', align='L')
pdf.ln(5)

# Weekend Note
pdf.set_font('helvetica', 'B', 12)
pdf.cell(0, 8, 'Weekend Note', new_x="LMARGIN", new_y="NEXT", align='L')
pdf.set_font('helvetica', '', 11)
pdf.multi_cell(w=190, h=6, text='Markets are closed Saturday/Sunday. Monday pre-market will reflect any weekend developments.', align='L')
pdf.ln(10)

# Footer
pdf.set_font('helvetica', 'I', 10)
pdf.cell(0, 10, 'Generated by Daily Brief Agent | May 9, 2026', new_x="LMARGIN", new_y="NEXT", align='C')

# Save
output_path = r'C:\Users\thadd\OneDrive\Desktop\Spocks Reports\daily-brief-2026-05-09.pdf'
pdf.output(output_path)
print(f'PDF generated: {output_path}')
